modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="genshin_nature"
version="1.5.0"
displayName="Genshin Nature"
displayURL="https://github.com/PrimogemStudio"
logoFile="logo.png"
credits="Mihoyo & The Genshin Mineverse team"
authors="Primogem Studio"
description="Genshin Impact enemies and plants in Minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.genshin_nature]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.92,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.genshin_nature]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration