
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.genshinnature.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.effect.MobEffect;
import net.minecraft.core.registries.Registries;

import net.mcreator.genshinnature.potion.WitheringprotectionMobEffect;
import net.mcreator.genshinnature.potion.WitchsscorchinghateffectMobEffect;
import net.mcreator.genshinnature.potion.WitchsheartflameseffectMobEffect;
import net.mcreator.genshinnature.potion.WitchsflowerofblazeeffectMobEffect;
import net.mcreator.genshinnature.potion.WitchseverburningplumeeffectMobEffect;
import net.mcreator.genshinnature.potion.WitchsendtimeeffectMobEffect;
import net.mcreator.genshinnature.potion.WisedoctorspinioneffectMobEffect;
import net.mcreator.genshinnature.potion.WinestainedtricorneeffectMobEffect;
import net.mcreator.genshinnature.potion.WetMobEffect;
import net.mcreator.genshinnature.potion.WanderersstringkettleeffectMobEffect;
import net.mcreator.genshinnature.potion.ViridescentvenerersvesseleffectMobEffect;
import net.mcreator.genshinnature.potion.ViridescentvenerersdiademeffectMobEffect;
import net.mcreator.genshinnature.potion.ViridescentvenerersdeterminationeffectMobEffect;
import net.mcreator.genshinnature.potion.ViridescentarrowfeathereffectMobEffect;
import net.mcreator.genshinnature.potion.TinymiraclesgobleteffectMobEffect;
import net.mcreator.genshinnature.potion.TinymiraclesearringseffectMobEffect;
import net.mcreator.genshinnature.potion.TiaraoftorrentseffectMobEffect;
import net.mcreator.genshinnature.potion.TiaraofthundereffectMobEffect;
import net.mcreator.genshinnature.potion.TiaraoffrosteffectMobEffect;
import net.mcreator.genshinnature.potion.TiaraofflameeffectMobEffect;
import net.mcreator.genshinnature.potion.ThundersummonerscrowneffectMobEffect;
import net.mcreator.genshinnature.potion.ThundersoothersplumeeffectMobEffect;
import net.mcreator.genshinnature.potion.ThundersoothershearteffectMobEffect;
import net.mcreator.genshinnature.potion.ThundersoothersgobleteffectMobEffect;
import net.mcreator.genshinnature.potion.ThundersoothersdiademeffectMobEffect;
import net.mcreator.genshinnature.potion.ThunderbirdsmercyeffectMobEffect;
import net.mcreator.genshinnature.potion.ThesunkenyearseffectMobEffect;
import net.mcreator.genshinnature.potion.SurvivorofcatastropheeffectMobEffect;
import net.mcreator.genshinnature.potion.SurpassingcupeffectMobEffect;
import net.mcreator.genshinnature.potion.SundialofenduringjadeeffectMobEffect;
import net.mcreator.genshinnature.potion.SummernightswaterballooneffectMobEffect;
import net.mcreator.genshinnature.potion.SummernightsmomenteffectMobEffect;
import net.mcreator.genshinnature.potion.SummernightsmaskeffectMobEffect;
import net.mcreator.genshinnature.potion.SummernightsfinaleeffectMobEffect;
import net.mcreator.genshinnature.potion.SummernightsbloomeffectMobEffect;
import net.mcreator.genshinnature.potion.SongoflifeeffectMobEffect;
import net.mcreator.genshinnature.potion.SnowsweptmemoryeffectMobEffect;
import net.mcreator.genshinnature.potion.SkeletalhateffectMobEffect;
import net.mcreator.genshinnature.potion.SheercoldMobEffect;
import net.mcreator.genshinnature.potion.ShadowofthesandkingeffectMobEffect;
import net.mcreator.genshinnature.potion.ScholarofvineseffectMobEffect;
import net.mcreator.genshinnature.potion.ScarletvesseleffectMobEffect;
import net.mcreator.genshinnature.potion.RoyalsilverurneffectMobEffect;
import net.mcreator.genshinnature.potion.RoyalmasqueeffectMobEffect;
import net.mcreator.genshinnature.potion.PyrovisioneffectMobEffect;
import net.mcreator.genshinnature.potion.PyroresistanceMobEffect;
import net.mcreator.genshinnature.potion.PyrodelusioneffectMobEffect;
import net.mcreator.genshinnature.potion.PlumeofluxuryeffectMobEffect;
import net.mcreator.genshinnature.potion.PearlcageeffectMobEffect;
import net.mcreator.genshinnature.potion.OutsetofthebraveeffectMobEffect;
import net.mcreator.genshinnature.potion.OrnatekabutoeffectMobEffect;
import net.mcreator.genshinnature.potion.OmenofthunderstormeffectMobEffect;
import net.mcreator.genshinnature.potion.NoblespledgingvesseleffectMobEffect;
import net.mcreator.genshinnature.potion.MomentofcessationeffectMobEffect;
import net.mcreator.genshinnature.potion.MockingmaskeffectMobEffect;
import net.mcreator.genshinnature.potion.MaskofsolitudebasalteffectMobEffect;
import net.mcreator.genshinnature.potion.MaidensfleetingleisureeffectMobEffect;
import net.mcreator.genshinnature.potion.MaidensfadingbeautyeffectMobEffect;
import net.mcreator.genshinnature.potion.LuckydogssilvercircleteffectMobEffect;
import net.mcreator.genshinnature.potion.LuckydogsgobleteffectMobEffect;
import net.mcreator.genshinnature.potion.LavawalkerswisdomeffectMobEffect;
import net.mcreator.genshinnature.potion.LavawalkerstormenteffectMobEffect;
import net.mcreator.genshinnature.potion.LavawalkerssalvationeffectMobEffect;
import net.mcreator.genshinnature.potion.LavawalkersresolutioneffectMobEffect;
import net.mcreator.genshinnature.potion.LavawalkersepiphanyeffectMobEffect;
import net.mcreator.genshinnature.potion.LaurelcoroneteffectMobEffect;
import net.mcreator.genshinnature.potion.LampofthelosteffectMobEffect;
import net.mcreator.genshinnature.potion.LabyrinthwayfarereffectMobEffect;
import net.mcreator.genshinnature.potion.InstructorsteacupeffectMobEffect;
import net.mcreator.genshinnature.potion.InstructorscapeffectMobEffect;
import net.mcreator.genshinnature.potion.InremembranceofviridescentfieldseffectMobEffect;
import net.mcreator.genshinnature.potion.IcebreakersresolveeffectMobEffect;
import net.mcreator.genshinnature.potion.HydrovisioneffectMobEffect;
import net.mcreator.genshinnature.potion.HydroresistanceMobEffect;
import net.mcreator.genshinnature.potion.HydrodelusioneffectMobEffect;
import net.mcreator.genshinnature.potion.HourofsoothingthundereffectMobEffect;
import net.mcreator.genshinnature.potion.HourglassofthundereffectMobEffect;
import net.mcreator.genshinnature.potion.HopefulhearteffectMobEffect;
import net.mcreator.genshinnature.potion.HoneyedfinalfeasteffectMobEffect;
import net.mcreator.genshinnature.potion.GustofnostalgiaeffectMobEffect;
import net.mcreator.genshinnature.potion.GobletofthunderingdeepeffectMobEffect;
import net.mcreator.genshinnature.potion.GobletofthesojournereffectMobEffect;
import net.mcreator.genshinnature.potion.GobletofchiseledcrageffectMobEffect;
import net.mcreator.genshinnature.potion.GladiatorstriumphuseffectMobEffect;
import net.mcreator.genshinnature.potion.GladiatorsintoxicationeffectMobEffect;
import net.mcreator.genshinnature.potion.GildedcorsageeffectMobEffect;
import net.mcreator.genshinnature.potion.GeovisioneffectMobEffect;
import net.mcreator.genshinnature.potion.GeoresistanceMobEffect;
import net.mcreator.genshinnature.potion.GeodelusioneffectMobEffect;
import net.mcreator.genshinnature.potion.GeneralsancienthelmeffectMobEffect;
import net.mcreator.genshinnature.potion.GamblersearringseffectMobEffect;
import net.mcreator.genshinnature.potion.GamblersdicecupeffectMobEffect;
import net.mcreator.genshinnature.potion.FrozenhomelanddemiseeffectMobEffect;
import net.mcreator.genshinnature.potion.FrostweaveddignityeffectMobEffect;
import net.mcreator.genshinnature.potion.FlowingringseffectMobEffect;
import net.mcreator.genshinnature.potion.FlowerofcrevicedcliffeffectMobEffect;
import net.mcreator.genshinnature.potion.FeatherofjudgmenteffectMobEffect;
import net.mcreator.genshinnature.potion.FeatherofjaggedpeakseffectMobEffect;
import net.mcreator.genshinnature.potion.ExilesgobleteffectMobEffect;
import net.mcreator.genshinnature.potion.ExilescircleteffectMobEffect;
import net.mcreator.genshinnature.potion.ElectrovisioneffectMobEffect;
import net.mcreator.genshinnature.potion.ElectroresistanceMobEffect;
import net.mcreator.genshinnature.potion.ElectrodelusioneffectMobEffect;
import net.mcreator.genshinnature.potion.ElectrifiedMobEffect;
import net.mcreator.genshinnature.potion.DreamingsteelbloomeffectMobEffect;
import net.mcreator.genshinnature.potion.DendrovisioneffectMobEffect;
import net.mcreator.genshinnature.potion.DendroresistanceMobEffect;
import net.mcreator.genshinnature.potion.DendrodelusioneffectMobEffect;
import net.mcreator.genshinnature.potion.CryovisioneffectMobEffect;
import net.mcreator.genshinnature.potion.CryoresistanceMobEffect;
import net.mcreator.genshinnature.potion.CryodelusioneffectMobEffect;
import net.mcreator.genshinnature.potion.CrownofwatatsumieffectMobEffect;
import net.mcreator.genshinnature.potion.CrownofthebraveeffectMobEffect;
import net.mcreator.genshinnature.potion.CrownofpartingeffectMobEffect;
import net.mcreator.genshinnature.potion.CoppercompasseffectMobEffect;
import net.mcreator.genshinnature.potion.ConductorstophateffectMobEffect;
import net.mcreator.genshinnature.potion.ColdprotectionMobEffect;
import net.mcreator.genshinnature.potion.ChaliceofthefonteffectMobEffect;
import net.mcreator.genshinnature.potion.CapriciousvisageeffectMobEffect;
import net.mcreator.genshinnature.potion.CalabashofawakeningeffectMobEffect;
import net.mcreator.genshinnature.potion.BrokenrimesechoeffectMobEffect;
import net.mcreator.genshinnature.potion.BloomtimeseffectMobEffect;
import net.mcreator.genshinnature.potion.BloodstainedironmaskeffectMobEffect;
import net.mcreator.genshinnature.potion.BloodstainedchevaliersgobleteffectMobEffect;
import net.mcreator.genshinnature.potion.BerserkersbonegobleteffectMobEffect;
import net.mcreator.genshinnature.potion.BerserkersbattlemaskeffectMobEffect;
import net.mcreator.genshinnature.potion.AtimeofinsighteffectMobEffect;
import net.mcreator.genshinnature.potion.AnemovisioneffectMobEffect;
import net.mcreator.genshinnature.potion.AnemoresistanceMobEffect;
import net.mcreator.genshinnature.potion.AnemodelusioneffectMobEffect;
import net.mcreator.genshinnature.potion.AdventurersgoldengobleteffectMobEffect;
import net.mcreator.genshinnature.potion.AdventurersbandanaeffectMobEffect;
import net.mcreator.genshinnature.GenshinNatureMod;

public class GenshinNatureModMobEffects {
	public static final DeferredRegister<MobEffect> REGISTRY = DeferredRegister.create(Registries.MOB_EFFECT, GenshinNatureMod.MODID);
	public static final DeferredHolder<MobEffect, MobEffect> ADVENTURERSGOLDENGOBLETEFFECT = REGISTRY.register("adventurersgoldengobleteffect", () -> new AdventurersgoldengobleteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ADVENTURERSBANDANAEFFECT = REGISTRY.register("adventurersbandanaeffect", () -> new AdventurersbandanaeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LUCKYDOGSGOBLETEFFECT = REGISTRY.register("luckydogsgobleteffect", () -> new LuckydogsgobleteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LUCKYDOGSSILVERCIRCLETEFFECT = REGISTRY.register("luckydogssilvercircleteffect", () -> new LuckydogssilvercircleteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GOBLETOFTHESOJOURNEREFFECT = REGISTRY.register("gobletofthesojournereffect", () -> new GobletofthesojournereffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CROWNOFPARTINGEFFECT = REGISTRY.register("crownofpartingeffect", () -> new CrownofpartingeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> INSTRUCTORSTEACUPEFFECT = REGISTRY.register("instructorsteacupeffect", () -> new InstructorsteacupeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> INSTRUCTORSCAPEFFECT = REGISTRY.register("instructorscapeffect", () -> new InstructorscapeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> BERSERKERSBONEGOBLETEFFECT = REGISTRY.register("berserkersbonegobleteffect", () -> new BerserkersbonegobleteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> BERSERKERSBATTLEMASKEFFECT = REGISTRY.register("berserkersbattlemaskeffect", () -> new BerserkersbattlemaskeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> EXILESGOBLETEFFECT = REGISTRY.register("exilesgobleteffect", () -> new ExilesgobleteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> EXILESCIRCLETEFFECT = REGISTRY.register("exilescircleteffect", () -> new ExilescircleteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> TINYMIRACLESGOBLETEFFECT = REGISTRY.register("tinymiraclesgobleteffect", () -> new TinymiraclesgobleteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> TINYMIRACLESEARRINGSEFFECT = REGISTRY.register("tinymiraclesearringseffect", () -> new TinymiraclesearringseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> OUTSETOFTHEBRAVEEFFECT = REGISTRY.register("outsetofthebraveeffect", () -> new OutsetofthebraveeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CROWNOFTHEBRAVEEFFECT = REGISTRY.register("crownofthebraveeffect", () -> new CrownofthebraveeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GAMBLERSDICECUPEFFECT = REGISTRY.register("gamblersdicecupeffect", () -> new GamblersdicecupeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GAMBLERSEARRINGSEFFECT = REGISTRY.register("gamblersearringseffect", () -> new GamblersearringseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GLADIATORSINTOXICATIONEFFECT = REGISTRY.register("gladiatorsintoxicationeffect", () -> new GladiatorsintoxicationeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GLADIATORSTRIUMPHUSEFFECT = REGISTRY.register("gladiatorstriumphuseffect", () -> new GladiatorstriumphuseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> MAIDENSFLEETINGLEISUREEFFECT = REGISTRY.register("maidensfleetingleisureeffect", () -> new MaidensfleetingleisureeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> MAIDENSFADINGBEAUTYEFFECT = REGISTRY.register("maidensfadingbeautyeffect", () -> new MaidensfadingbeautyeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ROYALSILVERURNEFFECT = REGISTRY.register("royalsilverurneffect", () -> new RoyalsilverurneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ROYALMASQUEEFFECT = REGISTRY.register("royalmasqueeffect", () -> new RoyalmasqueeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> BLOODSTAINEDCHEVALIERSGOBLETEFFECT = REGISTRY.register("bloodstainedchevaliersgobleteffect", () -> new BloodstainedchevaliersgobleteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> BLOODSTAINEDIRONMASKEFFECT = REGISTRY.register("bloodstainedironmaskeffect", () -> new BloodstainedironmaskeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WANDERERSSTRINGKETTLEEFFECT = REGISTRY.register("wanderersstringkettleeffect", () -> new WanderersstringkettleeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CONDUCTORSTOPHATEFFECT = REGISTRY.register("conductorstophateffect", () -> new ConductorstophateffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> NOBLESPLEDGINGVESSELEFFECT = REGISTRY.register("noblespledgingvesseleffect", () -> new NoblespledgingvesseleffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GENERALSANCIENTHELMEFFECT = REGISTRY.register("generalsancienthelmeffect", () -> new GeneralsancienthelmeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WISEDOCTORSPINIONEFFECT = REGISTRY.register("wisedoctorspinioneffect", () -> new WisedoctorspinioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> MOMENTOFCESSATIONEFFECT = REGISTRY.register("momentofcessationeffect", () -> new MomentofcessationeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SURPASSINGCUPEFFECT = REGISTRY.register("surpassingcupeffect", () -> new SurpassingcupeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> MOCKINGMASKEFFECT = REGISTRY.register("mockingmaskeffect", () -> new MockingmaskeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SCARLETVESSELEFFECT = REGISTRY.register("scarletvesseleffect", () -> new ScarletvesseleffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ORNATEKABUTOEFFECT = REGISTRY.register("ornatekabutoeffect", () -> new OrnatekabutoeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HOPEFULHEARTEFFECT = REGISTRY.register("hopefulhearteffect", () -> new HopefulhearteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CAPRICIOUSVISAGEEFFECT = REGISTRY.register("capriciousvisageeffect", () -> new CapriciousvisageeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> INREMEMBRANCEOFVIRIDESCENTFIELDSEFFECT = REGISTRY.register("inremembranceofviridescentfieldseffect", () -> new InremembranceofviridescentfieldseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> VIRIDESCENTARROWFEATHEREFFECT = REGISTRY.register("viridescentarrowfeathereffect", () -> new ViridescentarrowfeathereffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> VIRIDESCENTVENERERSDETERMINATIONEFFECT = REGISTRY.register("viridescentvenerersdeterminationeffect", () -> new ViridescentvenerersdeterminationeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> VIRIDESCENTVENERERSVESSELEFFECT = REGISTRY.register("viridescentvenerersvesseleffect", () -> new ViridescentvenerersvesseleffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> VIRIDESCENTVENERERSDIADEMEFFECT = REGISTRY.register("viridescentvenerersdiademeffect", () -> new ViridescentvenerersdiademeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> THUNDERBIRDSMERCYEFFECT = REGISTRY.register("thunderbirdsmercyeffect", () -> new ThunderbirdsmercyeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SURVIVOROFCATASTROPHEEFFECT = REGISTRY.register("survivorofcatastropheeffect", () -> new SurvivorofcatastropheeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HOURGLASSOFTHUNDEREFFECT = REGISTRY.register("hourglassofthundereffect", () -> new HourglassofthundereffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> OMENOFTHUNDERSTORMEFFECT = REGISTRY.register("omenofthunderstormeffect", () -> new OmenofthunderstormeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> THUNDERSUMMONERSCROWNEFFECT = REGISTRY.register("thundersummonerscrowneffect", () -> new ThundersummonerscrowneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> THUNDERSOOTHERSHEARTEFFECT = REGISTRY.register("thundersoothershearteffect", () -> new ThundersoothershearteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> THUNDERSOOTHERSPLUMEEFFECT = REGISTRY.register("thundersoothersplumeeffect", () -> new ThundersoothersplumeeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HOUROFSOOTHINGTHUNDEREFFECT = REGISTRY.register("hourofsoothingthundereffect", () -> new HourofsoothingthundereffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> THUNDERSOOTHERSGOBLETEFFECT = REGISTRY.register("thundersoothersgobleteffect", () -> new ThundersoothersgobleteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> THUNDERSOOTHERSDIADEMEFFECT = REGISTRY.register("thundersoothersdiademeffect", () -> new ThundersoothersdiademeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SHEERCOLD = REGISTRY.register("sheercold", () -> new SheercoldMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> COLDPROTECTION = REGISTRY.register("coldprotection", () -> new ColdprotectionMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WITCHSFLOWEROFBLAZEEFFECT = REGISTRY.register("witchsflowerofblazeeffect", () -> new WitchsflowerofblazeeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WITCHSEVERBURNINGPLUMEEFFECT = REGISTRY.register("witchseverburningplumeeffect", () -> new WitchseverburningplumeeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WITCHSENDTIMEEFFECT = REGISTRY.register("witchsendtimeeffect", () -> new WitchsendtimeeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WITCHSHEARTFLAMESEFFECT = REGISTRY.register("witchsheartflameseffect", () -> new WitchsheartflameseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WITCHSSCORCHINGHATEFFECT = REGISTRY.register("witchsscorchinghateffect", () -> new WitchsscorchinghateffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LAVAWALKERSRESOLUTIONEFFECT = REGISTRY.register("lavawalkersresolutioneffect", () -> new LavawalkersresolutioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LAVAWALKERSSALVATIONEFFECT = REGISTRY.register("lavawalkerssalvationeffect", () -> new LavawalkerssalvationeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LAVAWALKERSTORMENTEFFECT = REGISTRY.register("lavawalkerstormenteffect", () -> new LavawalkerstormenteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LAVAWALKERSEPIPHANYEFFECT = REGISTRY.register("lavawalkersepiphanyeffect", () -> new LavawalkersepiphanyeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LAVAWALKERSWISDOMEFFECT = REGISTRY.register("lavawalkerswisdomeffect", () -> new LavawalkerswisdomeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> FLOWEROFCREVICEDCLIFFEFFECT = REGISTRY.register("flowerofcrevicedcliffeffect", () -> new FlowerofcrevicedcliffeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> FEATHEROFJAGGEDPEAKSEFFECT = REGISTRY.register("featherofjaggedpeakseffect", () -> new FeatherofjaggedpeakseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SUNDIALOFENDURINGJADEEFFECT = REGISTRY.register("sundialofenduringjadeeffect", () -> new SundialofenduringjadeeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GOBLETOFCHISELEDCRAGEFFECT = REGISTRY.register("gobletofchiseledcrageffect", () -> new GobletofchiseledcrageffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> MASKOFSOLITUDEBASALTEFFECT = REGISTRY.register("maskofsolitudebasalteffect", () -> new MaskofsolitudebasalteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SUMMERNIGHTSBLOOMEFFECT = REGISTRY.register("summernightsbloomeffect", () -> new SummernightsbloomeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SUMMERNIGHTSFINALEEFFECT = REGISTRY.register("summernightsfinaleeffect", () -> new SummernightsfinaleeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SUMMERNIGHTSMOMENTEFFECT = REGISTRY.register("summernightsmomenteffect", () -> new SummernightsmomenteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SUMMERNIGHTSWATERBALLOONEFFECT = REGISTRY.register("summernightswaterballooneffect", () -> new SummernightswaterballooneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SUMMERNIGHTSMASKEFFECT = REGISTRY.register("summernightsmaskeffect", () -> new SummernightsmaskeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SNOWSWEPTMEMORYEFFECT = REGISTRY.register("snowsweptmemoryeffect", () -> new SnowsweptmemoryeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ICEBREAKERSRESOLVEEFFECT = REGISTRY.register("icebreakersresolveeffect", () -> new IcebreakersresolveeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> FROZENHOMELANDDEMISEEFFECT = REGISTRY.register("frozenhomelanddemiseeffect", () -> new FrozenhomelanddemiseeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> FROSTWEAVEDDIGNITYEFFECT = REGISTRY.register("frostweaveddignityeffect", () -> new FrostweaveddignityeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> BROKENRIMESECHOEFFECT = REGISTRY.register("brokenrimesechoeffect", () -> new BrokenrimesechoeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ELECTRIFIED = REGISTRY.register("electrified", () -> new ElectrifiedMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> PYROVISIONEFFECT = REGISTRY.register("pyrovisioneffect", () -> new PyrovisioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HYDROVISIONEFFECT = REGISTRY.register("hydrovisioneffect", () -> new HydrovisioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ANEMOVISIONEFFECT = REGISTRY.register("anemovisioneffect", () -> new AnemovisioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ELECTROVISIONEFFECT = REGISTRY.register("electrovisioneffect", () -> new ElectrovisioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CRYOVISIONEFFECT = REGISTRY.register("cryovisioneffect", () -> new CryovisioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GEOVISIONEFFECT = REGISTRY.register("geovisioneffect", () -> new GeovisioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GILDEDCORSAGEEFFECT = REGISTRY.register("gildedcorsageeffect", () -> new GildedcorsageeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GUSTOFNOSTALGIAEFFECT = REGISTRY.register("gustofnostalgiaeffect", () -> new GustofnostalgiaeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> COPPERCOMPASSEFFECT = REGISTRY.register("coppercompasseffect", () -> new CoppercompasseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GOBLETOFTHUNDERINGDEEPEFFECT = REGISTRY.register("gobletofthunderingdeepeffect", () -> new GobletofthunderingdeepeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WINESTAINEDTRICORNEEFFECT = REGISTRY.register("winestainedtricorneeffect", () -> new WinestainedtricorneeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> TIARAOFFLAMEEFFECT = REGISTRY.register("tiaraofflameeffect", () -> new TiaraofflameeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> TIARAOFFROSTEFFECT = REGISTRY.register("tiaraoffrosteffect", () -> new TiaraoffrosteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> TIARAOFTHUNDEREFFECT = REGISTRY.register("tiaraofthundereffect", () -> new TiaraofthundereffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> TIARAOFTORRENTSEFFECT = REGISTRY.register("tiaraoftorrentseffect", () -> new TiaraoftorrentseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> BLOOMTIMESEFFECT = REGISTRY.register("bloomtimeseffect", () -> new BloomtimeseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> PLUMEOFLUXURYEFFECT = REGISTRY.register("plumeofluxuryeffect", () -> new PlumeofluxuryeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SONGOFLIFEEFFECT = REGISTRY.register("songoflifeeffect", () -> new SongoflifeeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CALABASHOFAWAKENINGEFFECT = REGISTRY.register("calabashofawakeningeffect", () -> new CalabashofawakeningeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SKELETALHATEFFECT = REGISTRY.register("skeletalhateffect", () -> new SkeletalhateffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> DENDROVISIONEFFECT = REGISTRY.register("dendrovisioneffect", () -> new DendrovisioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ANEMODELUSIONEFFECT = REGISTRY.register("anemodelusioneffect", () -> new AnemodelusioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CRYODELUSIONEFFECT = REGISTRY.register("cryodelusioneffect", () -> new CryodelusioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ELECTRODELUSIONEFFECT = REGISTRY.register("electrodelusioneffect", () -> new ElectrodelusioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GEODELUSIONEFFECT = REGISTRY.register("geodelusioneffect", () -> new GeodelusioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HYDRODELUSIONEFFECT = REGISTRY.register("hydrodelusioneffect", () -> new HydrodelusioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> PYRODELUSIONEFFECT = REGISTRY.register("pyrodelusioneffect", () -> new PyrodelusioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> DENDRODELUSIONEFFECT = REGISTRY.register("dendrodelusioneffect", () -> new DendrodelusioneffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WET = REGISTRY.register("wet", () -> new WetMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> PYRORESISTANCE = REGISTRY.register("pyroresistance", () -> new PyroresistanceMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HYDRORESISTANCE = REGISTRY.register("hydroresistance", () -> new HydroresistanceMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CRYORESISTANCE = REGISTRY.register("cryoresistance", () -> new CryoresistanceMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ANEMORESISTANCE = REGISTRY.register("anemoresistance", () -> new AnemoresistanceMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ELECTRORESISTANCE = REGISTRY.register("electroresistance", () -> new ElectroresistanceMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> GEORESISTANCE = REGISTRY.register("georesistance", () -> new GeoresistanceMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> DENDRORESISTANCE = REGISTRY.register("dendroresistance", () -> new DendroresistanceMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> PEARLCAGEEFFECT = REGISTRY.register("pearlcageeffect", () -> new PearlcageeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CROWNOFWATATSUMIEFFECT = REGISTRY.register("crownofwatatsumieffect", () -> new CrownofwatatsumieffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> CHALICEOFTHEFONTEFFECT = REGISTRY.register("chaliceofthefonteffect", () -> new ChaliceofthefonteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> FLOWINGRINGSEFFECT = REGISTRY.register("flowingringseffect", () -> new FlowingringseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> DREAMINGSTEELBLOOMEFFECT = REGISTRY.register("dreamingsteelbloomeffect", () -> new DreamingsteelbloomeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> FEATHEROFJUDGMENTEFFECT = REGISTRY.register("featherofjudgmenteffect", () -> new FeatherofjudgmenteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> THESUNKENYEARSEFFECT = REGISTRY.register("thesunkenyearseffect", () -> new ThesunkenyearseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> HONEYEDFINALFEASTEFFECT = REGISTRY.register("honeyedfinalfeasteffect", () -> new HoneyedfinalfeasteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SHADOWOFTHESANDKINGEFFECT = REGISTRY.register("shadowofthesandkingeffect", () -> new ShadowofthesandkingeffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LABYRINTHWAYFAREREFFECT = REGISTRY.register("labyrinthwayfarereffect", () -> new LabyrinthwayfarereffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> SCHOLAROFVINESEFFECT = REGISTRY.register("scholarofvineseffect", () -> new ScholarofvineseffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> ATIMEOFINSIGHTEFFECT = REGISTRY.register("atimeofinsighteffect", () -> new AtimeofinsighteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LAMPOFTHELOSTEFFECT = REGISTRY.register("lampofthelosteffect", () -> new LampofthelosteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> LAURELCORONETEFFECT = REGISTRY.register("laurelcoroneteffect", () -> new LaurelcoroneteffectMobEffect());
	public static final DeferredHolder<MobEffect, MobEffect> WITHERINGPROTECTION = REGISTRY.register("witheringprotection", () -> new WitheringprotectionMobEffect());
}
