
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.genshinnature.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.mcreator.genshinnature.block.ZohrahmushroomBlock;
import net.mcreator.genshinnature.block.ZhongliplushieBlock;
import net.mcreator.genshinnature.block.YunjinplushieBlock;
import net.mcreator.genshinnature.block.YumemiruwoodBlock;
import net.mcreator.genshinnature.block.YumemirutrapdoorBlock;
import net.mcreator.genshinnature.block.YumemirustairsBlock;
import net.mcreator.genshinnature.block.YumemiruslabBlock;
import net.mcreator.genshinnature.block.YumemiruplanksBlock;
import net.mcreator.genshinnature.block.YumemiruleavesBlock;
import net.mcreator.genshinnature.block.YumemirufencegateBlock;
import net.mcreator.genshinnature.block.YumemirufenceBlock;
import net.mcreator.genshinnature.block.YumemirudoorBlock;
import net.mcreator.genshinnature.block.YoimiyaplushieBlock;
import net.mcreator.genshinnature.block.YelanplushieBlock;
import net.mcreator.genshinnature.block.YanfeiplushieBlock;
import net.mcreator.genshinnature.block.YajnagrassBlock;
import net.mcreator.genshinnature.block.YaemikoplushieBlock;
import net.mcreator.genshinnature.block.XinyanplushieBlock;
import net.mcreator.genshinnature.block.XingqiuplushieBlock;
import net.mcreator.genshinnature.block.XiaoplushieBlock;
import net.mcreator.genshinnature.block.XiaolanternBlock;
import net.mcreator.genshinnature.block.XianglingplushieBlock;
import net.mcreator.genshinnature.block.WondrouslovelyflowerBlock;
import net.mcreator.genshinnature.block.WitheringstoppedBlock;
import net.mcreator.genshinnature.block.WitheringexpandingBlock;
import net.mcreator.genshinnature.block.Witheringexpanding4Block;
import net.mcreator.genshinnature.block.Witheringexpanding3Block;
import net.mcreator.genshinnature.block.Witheringexpanding2Block;
import net.mcreator.genshinnature.block.WispspawnerBlock;
import net.mcreator.genshinnature.block.WindwheelasterBlock;
import net.mcreator.genshinnature.block.WindblumefestivalcommemorativeballoonBlock;
import net.mcreator.genshinnature.block.WhiteironchunkBlock;
import net.mcreator.genshinnature.block.WaveriderwaypointBlock;
import net.mcreator.genshinnature.block.ViparyasBlock;
import net.mcreator.genshinnature.block.VioletgrassBlock;
import net.mcreator.genshinnature.block.VentiplushieBlock;
import net.mcreator.genshinnature.block.TrustyportablelampBlock;
import net.mcreator.genshinnature.block.TrounceblossomBlock;
import net.mcreator.genshinnature.block.TreesofazurejadeBlock;
import net.mcreator.genshinnature.block.TokoyolegumeBlock;
import net.mcreator.genshinnature.block.TimedobsidianBlock;
import net.mcreator.genshinnature.block.TimediceBlock;
import net.mcreator.genshinnature.block.TimedcobblestoneBlock;
import net.mcreator.genshinnature.block.TighnariplushieBlock;
import net.mcreator.genshinnature.block.ThroughthewhitefoamthejadebutterflysoarsBlock;
import net.mcreator.genshinnature.block.ThricedyedcrimsonsnowmeltBlock;
import net.mcreator.genshinnature.block.ThomaplushieBlock;
import net.mcreator.genshinnature.block.TheblueoceanstreasureBlock;
import net.mcreator.genshinnature.block.TheasterssighBlock;
import net.mcreator.genshinnature.block.TeahouseroundstoolpainpointreductionBlock;
import net.mcreator.genshinnature.block.TeahousecushionnightwovenBlock;
import net.mcreator.genshinnature.block.TartagliaplushieBlock;
import net.mcreator.genshinnature.block.TalentsblockBlock;
import net.mcreator.genshinnature.block.SweetflowerBlock;
import net.mcreator.genshinnature.block.SumeruroseBlock;
import net.mcreator.genshinnature.block.SucroseplushieBlock;
import net.mcreator.genshinnature.block.SubrosiumBlock;
import net.mcreator.genshinnature.block.StrangetoothBlock;
import net.mcreator.genshinnature.block.StraightshooterBlock;
import net.mcreator.genshinnature.block.StarsplinterironBlock;
import net.mcreator.genshinnature.block.StarsilverBlock;
import net.mcreator.genshinnature.block.StarshroomBlock;
import net.mcreator.genshinnature.block.StarconchBlock;
import net.mcreator.genshinnature.block.SquareyumemirustoolBlock;
import net.mcreator.genshinnature.block.SpawnprimaltempleBlock;
import net.mcreator.genshinnature.block.SouvenirshopBlock;
import net.mcreator.genshinnature.block.SnapdragonBlock;
import net.mcreator.genshinnature.block.SmoothwoodenbenchBlock;
import net.mcreator.genshinnature.block.SmoothstonebenchBlock;
import net.mcreator.genshinnature.block.SmalllampgrassBlock;
import net.mcreator.genshinnature.block.SilkflowerBlock;
import net.mcreator.genshinnature.block.SilapnaBlock;
import net.mcreator.genshinnature.block.ShootingbubbleBlock;
import net.mcreator.genshinnature.block.ShenheplushieBlock;
import net.mcreator.genshinnature.block.SeelietreasureBlock;
import net.mcreator.genshinnature.block.Seelietreasure4Block;
import net.mcreator.genshinnature.block.Seelietreasure3Block;
import net.mcreator.genshinnature.block.Seelietreasure2Block;
import net.mcreator.genshinnature.block.SeaganodermaBlock;
import net.mcreator.genshinnature.block.ScarletscentedfandanceBlock;
import net.mcreator.genshinnature.block.ScarletquartzBlock;
import net.mcreator.genshinnature.block.SayuplushieBlock;
import net.mcreator.genshinnature.block.SaraplushieBlock;
import net.mcreator.genshinnature.block.SandbearerwoodBlock;
import net.mcreator.genshinnature.block.SandbearertrapdoorBlock;
import net.mcreator.genshinnature.block.SandbearerstairsBlock;
import net.mcreator.genshinnature.block.SandbearerslabBlock;
import net.mcreator.genshinnature.block.SandbearerplanksBlock;
import net.mcreator.genshinnature.block.SandbearerleavesBlock;
import net.mcreator.genshinnature.block.SandbearerfencegateBlock;
import net.mcreator.genshinnature.block.SandbearerfenceBlock;
import net.mcreator.genshinnature.block.SandbearerdoorBlock;
import net.mcreator.genshinnature.block.SakurabloomBlock;
import net.mcreator.genshinnature.block.RukkhashavamushroomsBlock;
import net.mcreator.genshinnature.block.RuinserpentspawnerBlock;
import net.mcreator.genshinnature.block.Ruinserpentspawner3Block;
import net.mcreator.genshinnature.block.Ruinserpentspawner2Block;
import net.mcreator.genshinnature.block.Ruinserpentspawner1Block;
import net.mcreator.genshinnature.block.RuinbrazierBlock;
import net.mcreator.genshinnature.block.RosariaplushieBlock;
import net.mcreator.genshinnature.block.RockpillarpearlBlock;
import net.mcreator.genshinnature.block.RedpinewoodroundstoolBlock;
import net.mcreator.genshinnature.block.RedcafecupBlock;
import net.mcreator.genshinnature.block.RazorplushieBlock;
import net.mcreator.genshinnature.block.RaidenplushieBlock;
import net.mcreator.genshinnature.block.RadiantspincrystalBlock;
import net.mcreator.genshinnature.block.QiqiplushieBlock;
import net.mcreator.genshinnature.block.QingxinBlock;
import net.mcreator.genshinnature.block.PyromonumentBlock;
import net.mcreator.genshinnature.block.PyrohypostasisblockBlock;
import net.mcreator.genshinnature.block.PyroboomblossomBlock;
import net.mcreator.genshinnature.block.PlushieslootboxBlock;
import net.mcreator.genshinnature.block.PinediningchairBlock;
import net.mcreator.genshinnature.block.PinebackedteachairBlock;
import net.mcreator.genshinnature.block.PillarstoneBlock;
import net.mcreator.genshinnature.block.PhilanemomushroomBlock;
import net.mcreator.genshinnature.block.PerpetualmechanicalarrayblockBlock;
import net.mcreator.genshinnature.block.PaimonplushieBlock;
import net.mcreator.genshinnature.block.PadisarahBlock;
import net.mcreator.genshinnature.block.OtogiwoodBlock;
import net.mcreator.genshinnature.block.OtogitrapdoorBlock;
import net.mcreator.genshinnature.block.OtogistairsBlock;
import net.mcreator.genshinnature.block.OtogislabBlock;
import net.mcreator.genshinnature.block.OtogirakushisquaretableBlock;
import net.mcreator.genshinnature.block.OtogirakushisquarestoolBlock;
import net.mcreator.genshinnature.block.OtogiplanksBlock;
import net.mcreator.genshinnature.block.OtogileavesBlock;
import net.mcreator.genshinnature.block.OtogifencegateBlock;
import net.mcreator.genshinnature.block.OtogifenceBlock;
import net.mcreator.genshinnature.block.OtogidoorBlock;
import net.mcreator.genshinnature.block.OozingconcretionsbigBlock;
import net.mcreator.genshinnature.block.OozingconcretionsBlock;
import net.mcreator.genshinnature.block.OfpromisesunkeptthenightflowersspeakBlock;
import net.mcreator.genshinnature.block.NoelleplushieBlock;
import net.mcreator.genshinnature.block.NoctilucousjadeBlock;
import net.mcreator.genshinnature.block.NingguangplushieBlock;
import net.mcreator.genshinnature.block.NilouplushieBlock;
import net.mcreator.genshinnature.block.NilotpalalotusBlock;
import net.mcreator.genshinnature.block.NightofthepartypumpkinsBlock;
import net.mcreator.genshinnature.block.NakuweedBlock;
import net.mcreator.genshinnature.block.NahidaplushieBlock;
import net.mcreator.genshinnature.block.MysteriouscarvingBlock;
import net.mcreator.genshinnature.block.MonaplushieBlock;
import net.mcreator.genshinnature.block.MobspawnergenshinBlock;
import net.mcreator.genshinnature.block.MistflowerBlock;
import net.mcreator.genshinnature.block.MintBlock;
import net.mcreator.genshinnature.block.MiasmictumorspawnblockBlock;
import net.mcreator.genshinnature.block.MelancholythedewgrassshadowingBlock;
import net.mcreator.genshinnature.block.MauvelutesedgeshroomBlock;
import net.mcreator.genshinnature.block.MatsutakeBlock;
import net.mcreator.genshinnature.block.MaplewoodritualdrumfestivemusicBlock;
import net.mcreator.genshinnature.block.MaplewoodchandelierillumeBlock;
import net.mcreator.genshinnature.block.MaplewoodBlock;
import net.mcreator.genshinnature.block.MapletrapdoorBlock;
import net.mcreator.genshinnature.block.MaplestairsBlock;
import net.mcreator.genshinnature.block.MapleslabBlock;
import net.mcreator.genshinnature.block.MapleplanksBlock;
import net.mcreator.genshinnature.block.MapleleavesBlock;
import net.mcreator.genshinnature.block.MaplefencegateBlock;
import net.mcreator.genshinnature.block.MaplefenceBlock;
import net.mcreator.genshinnature.block.MapledoorBlock;
import net.mcreator.genshinnature.block.MagicalcrystalchunkBlock;
import net.mcreator.genshinnature.block.LumineplushieBlock;
import net.mcreator.genshinnature.block.LumenstoneBlock;
import net.mcreator.genshinnature.block.Lumenstone5Block;
import net.mcreator.genshinnature.block.Lumenstone15Block;
import net.mcreator.genshinnature.block.Lumenstone10Block;
import net.mcreator.genshinnature.block.LumensparoreBlock;
import net.mcreator.genshinnature.block.LumensparblockBlock;
import net.mcreator.genshinnature.block.LotusheadBlock;
import net.mcreator.genshinnature.block.LivingbubblespawnerBlock;
import net.mcreator.genshinnature.block.LiulipavilionsandbearerfloorlampBlock;
import net.mcreator.genshinnature.block.LisaplushieBlock;
import net.mcreator.genshinnature.block.LeylineoreendBlock;
import net.mcreator.genshinnature.block.LeylineoreBlock;
import net.mcreator.genshinnature.block.LeylinemineralblockBlock;
import net.mcreator.genshinnature.block.LaylaplushieBlock;
import net.mcreator.genshinnature.block.KukiplushieBlock;
import net.mcreator.genshinnature.block.KokomiplushieBlock;
import net.mcreator.genshinnature.block.KleeplushieBlock;
import net.mcreator.genshinnature.block.KeqingplushieBlock;
import net.mcreator.genshinnature.block.KazuhaplushieBlock;
import net.mcreator.genshinnature.block.KalpalatalotusBlock;
import net.mcreator.genshinnature.block.KaeyaplushieBlock;
import net.mcreator.genshinnature.block.JueyunchiliBlock;
import net.mcreator.genshinnature.block.JeanplushieBlock;
import net.mcreator.genshinnature.block.IttoplushieBlock;
import net.mcreator.genshinnature.block.IronchunkBlock;
import net.mcreator.genshinnature.block.HydrotileBlock;
import net.mcreator.genshinnature.block.HydromonumentBlock;
import net.mcreator.genshinnature.block.HydrohypostasisblockBlock;
import net.mcreator.genshinnature.block.HydroamberBlock;
import net.mcreator.genshinnature.block.HutaoplushieBlock;
import net.mcreator.genshinnature.block.HotpodBlock;
import net.mcreator.genshinnature.block.HorsetailBlock;
import net.mcreator.genshinnature.block.HomeawayfromhomeBlock;
import net.mcreator.genshinnature.block.HellcatplushieBlock;
import net.mcreator.genshinnature.block.HeizouplushieBlock;
import net.mcreator.genshinnature.block.GuobaplushieBlock;
import net.mcreator.genshinnature.block.GreencatplushieBlock;
import net.mcreator.genshinnature.block.GreencafecupBlock;
import net.mcreator.genshinnature.block.GorouplushieBlock;
import net.mcreator.genshinnature.block.GoogoltableBlock;
import net.mcreator.genshinnature.block.GoogolchairBlock;
import net.mcreator.genshinnature.block.GoldenwolflordstructurespawnBlock;
import net.mcreator.genshinnature.block.GoldenroseseedsBlock;
import net.mcreator.genshinnature.block.GoldenhousespawnerBlock;
import net.mcreator.genshinnature.block.GoldenattackerspawnerBlock;
import net.mcreator.genshinnature.block.Goldenattackerspawner4Block;
import net.mcreator.genshinnature.block.Goldenattackerspawner3Block;
import net.mcreator.genshinnature.block.Goldenattackerspawner2Block;
import net.mcreator.genshinnature.block.Goldenattackerspawner1Block;
import net.mcreator.genshinnature.block.GlazelilyBlock;
import net.mcreator.genshinnature.block.GlassshieldBlock;
import net.mcreator.genshinnature.block.GeoshrineblockBlock;
import net.mcreator.genshinnature.block.GeomonumentBlock;
import net.mcreator.genshinnature.block.GeohypostasisblockBlock;
import net.mcreator.genshinnature.block.GeoculusBlock;
import net.mcreator.genshinnature.block.GenshinseagrassBlock;
import net.mcreator.genshinnature.block.GenshinleavesBlock;
import net.mcreator.genshinnature.block.GanyuplushieBlock;
import net.mcreator.genshinnature.block.FullseelietreasureBlock;
import net.mcreator.genshinnature.block.FragrantcedarwoodBlock;
import net.mcreator.genshinnature.block.FragrantcedarvegetablerackBlock;
import net.mcreator.genshinnature.block.FragrantcedartrapdoorBlock;
import net.mcreator.genshinnature.block.FragrantcedarstairsBlock;
import net.mcreator.genshinnature.block.FragrantcedarslabBlock;
import net.mcreator.genshinnature.block.FragrantcedarplanksBlock;
import net.mcreator.genshinnature.block.FragrantcedarleavesBlock;
import net.mcreator.genshinnature.block.FragrantcedarfencegateBlock;
import net.mcreator.genshinnature.block.FragrantcedarfenceBlock;
import net.mcreator.genshinnature.block.FragrantcedardoorBlock;
import net.mcreator.genshinnature.block.FoundationsofstonepathofcultivationBlock;
import net.mcreator.genshinnature.block.FoundationsofstonedoubletimeBlock;
import net.mcreator.genshinnature.block.FluorescentfungusBlock;
import net.mcreator.genshinnature.block.FloraconverterBlock;
import net.mcreator.genshinnature.block.FloatysplodyBlock;
import net.mcreator.genshinnature.block.FlamingflowerBlock;
import net.mcreator.genshinnature.block.FishingblockBlock;
import net.mcreator.genshinnature.block.FischlplushieBlock;
import net.mcreator.genshinnature.block.FirwoodBlock;
import net.mcreator.genshinnature.block.FirtrapdoorBlock;
import net.mcreator.genshinnature.block.FirstairsBlock;
import net.mcreator.genshinnature.block.FirslabBlock;
import net.mcreator.genshinnature.block.FirplanksBlock;
import net.mcreator.genshinnature.block.FirleavesBlock;
import net.mcreator.genshinnature.block.FirfencegateBlock;
import net.mcreator.genshinnature.block.FirfenceBlock;
import net.mcreator.genshinnature.block.FirdoorBlock;
import net.mcreator.genshinnature.block.EvernightglitterboughBlock;
import net.mcreator.genshinnature.block.EvernightblazeshrubBlock;
import net.mcreator.genshinnature.block.EverlastingincenseBlock;
import net.mcreator.genshinnature.block.EuphoniumunboundwindingBlock;
import net.mcreator.genshinnature.block.EulaplushieBlock;
import net.mcreator.genshinnature.block.EmbroideredlanternloftygrandeurBlock;
import net.mcreator.genshinnature.block.ElectroshrineblockBlock;
import net.mcreator.genshinnature.block.ElectroshootBlock;
import net.mcreator.genshinnature.block.ElectromonumentBlock;
import net.mcreator.genshinnature.block.ElectrohypostasisblockBlock;
import net.mcreator.genshinnature.block.ElectroculusBlock;
import net.mcreator.genshinnature.block.ElectrocrystalBlock;
import net.mcreator.genshinnature.block.ElectroboomblossomBlock;
import net.mcreator.genshinnature.block.ElectricballspawnerBlock;
import net.mcreator.genshinnature.block.DoriplushieBlock;
import net.mcreator.genshinnature.block.DionaplushieBlock;
import net.mcreator.genshinnature.block.DilucplushieBlock;
import net.mcreator.genshinnature.block.DendroshrineblockBlock;
import net.mcreator.genshinnature.block.DendromonumentBlock;
import net.mcreator.genshinnature.block.DendroculusBlock;
import net.mcreator.genshinnature.block.DendrocoreBlock;
import net.mcreator.genshinnature.block.DendroboomblossomBlock;
import net.mcreator.genshinnature.block.DendrobiumBlock;
import net.mcreator.genshinnature.block.DecorativeoozingconcretionsbigBlock;
import net.mcreator.genshinnature.block.DecorativeoozingconcretionsBlock;
import net.mcreator.genshinnature.block.DarkmudcarpetBlock;
import net.mcreator.genshinnature.block.DarkmudBlock;
import net.mcreator.genshinnature.block.DainsleifplushieBlock;
import net.mcreator.genshinnature.block.CynoplushieBlock;
import net.mcreator.genshinnature.block.CuihuawoodBlock;
import net.mcreator.genshinnature.block.CuihuatrapdoorBlock;
import net.mcreator.genshinnature.block.CuihuastairsBlock;
import net.mcreator.genshinnature.block.CuihuaslabBlock;
import net.mcreator.genshinnature.block.CuihuaplanksBlock;
import net.mcreator.genshinnature.block.CuihualeavesBlock;
import net.mcreator.genshinnature.block.CuihuafencegateBlock;
import net.mcreator.genshinnature.block.CuihuafenceBlock;
import net.mcreator.genshinnature.block.CuihuadoorBlock;
import net.mcreator.genshinnature.block.CrystalmarrowBlock;
import net.mcreator.genshinnature.block.CrystalflylampBlock;
import net.mcreator.genshinnature.block.CrystalchunkBlock;
import net.mcreator.genshinnature.block.CryomonumentBlock;
import net.mcreator.genshinnature.block.CryohypostasisblockBlock;
import net.mcreator.genshinnature.block.CryoboomblossomBlock;
import net.mcreator.genshinnature.block.CrudedoubledeckerpalletBlock;
import net.mcreator.genshinnature.block.CrimsonardorBlock;
import net.mcreator.genshinnature.block.CrimsonagateoreBlock;
import net.mcreator.genshinnature.block.CrimsonagateblockBlock;
import net.mcreator.genshinnature.block.CradleofflowersBlock;
import net.mcreator.genshinnature.block.CorlapisBlock;
import net.mcreator.genshinnature.block.ColleiplushieBlock;
import net.mcreator.genshinnature.block.ClearblueafternoonBlock;
import net.mcreator.genshinnature.block.ChongyunplushieBlock;
import net.mcreator.genshinnature.block.ChildespawnerBlock;
import net.mcreator.genshinnature.block.Childespawner2Block;
import net.mcreator.genshinnature.block.Childespawner1Block;
import net.mcreator.genshinnature.block.ChallengeblockpyroBlock;
import net.mcreator.genshinnature.block.Challengeblockpyro3Block;
import net.mcreator.genshinnature.block.Challengeblockpyro2Block;
import net.mcreator.genshinnature.block.Challengeblockpyro1Block;
import net.mcreator.genshinnature.block.ChallengeblockhydroBlock;
import net.mcreator.genshinnature.block.Challengeblockhydro3Block;
import net.mcreator.genshinnature.block.Challengeblockhydro2Block;
import net.mcreator.genshinnature.block.Challengeblockhydro1Block;
import net.mcreator.genshinnature.block.ChallengeblockelectroBlock;
import net.mcreator.genshinnature.block.Challengeblockelectro3Block;
import net.mcreator.genshinnature.block.Challengeblockelectro2Block;
import net.mcreator.genshinnature.block.Challengeblockelectro1Block;
import net.mcreator.genshinnature.block.ChallengeblockcryoBlock;
import net.mcreator.genshinnature.block.Challengeblockcryo3Block;
import net.mcreator.genshinnature.block.Challengeblockcryo2Block;
import net.mcreator.genshinnature.block.Challengeblockcryo1Block;
import net.mcreator.genshinnature.block.CeciliaBlock;
import net.mcreator.genshinnature.block.CandleoflifeBlock;
import net.mcreator.genshinnature.block.CandaceplushieBlock;
import net.mcreator.genshinnature.block.CallalilyBlock;
import net.mcreator.genshinnature.block.CakefortravelerBlock;
import net.mcreator.genshinnature.block.Cakefortraveler3Block;
import net.mcreator.genshinnature.block.Cakefortraveler2Block;
import net.mcreator.genshinnature.block.CafepotBlock;
import net.mcreator.genshinnature.block.BluecafecupBlock;
import net.mcreator.genshinnature.block.BloattyfloattyexplodedBlock;
import net.mcreator.genshinnature.block.BloattyfloattyBlock;
import net.mcreator.genshinnature.block.BlankmonumentBlock;
import net.mcreator.genshinnature.block.BirdnestBlock;
import net.mcreator.genshinnature.block.BennettplushieBlock;
import net.mcreator.genshinnature.block.BeidouplushieBlock;
import net.mcreator.genshinnature.block.BarsamflowerBlock;
import net.mcreator.genshinnature.block.BarbaraplushieBlock;
import net.mcreator.genshinnature.block.BambootrapdoorBlock;
import net.mcreator.genshinnature.block.BamboostairsBlock;
import net.mcreator.genshinnature.block.BambooslabBlock;
import net.mcreator.genshinnature.block.BamboosegmentBlock;
import net.mcreator.genshinnature.block.BambooplanksBlock;
import net.mcreator.genshinnature.block.BamboooutdoortableBlock;
import net.mcreator.genshinnature.block.BamboofencegateBlock;
import net.mcreator.genshinnature.block.BamboofenceBlock;
import net.mcreator.genshinnature.block.BamboodoorBlock;
import net.mcreator.genshinnature.block.BaalstatueBlock;
import net.mcreator.genshinnature.block.AzhdahaspawnerBlock;
import net.mcreator.genshinnature.block.Azhdahaspawner5Block;
import net.mcreator.genshinnature.block.Azhdahaspawner4Block;
import net.mcreator.genshinnature.block.Azhdahaspawner3Block;
import net.mcreator.genshinnature.block.Azhdahaspawner2Block;
import net.mcreator.genshinnature.block.AzhdahaarenablockBlock;
import net.mcreator.genshinnature.block.AyatoplushieBlock;
import net.mcreator.genshinnature.block.AyakaplushieBlock;
import net.mcreator.genshinnature.block.ArtifactsblockBlock;
import net.mcreator.genshinnature.block.ArchaicstoneBlock;
import net.mcreator.genshinnature.block.AraliawoodBlock;
import net.mcreator.genshinnature.block.AraliatrapdoorBlock;
import net.mcreator.genshinnature.block.AraliastairsBlock;
import net.mcreator.genshinnature.block.AraliaslabBlock;
import net.mcreator.genshinnature.block.AraliaplanksBlock;
import net.mcreator.genshinnature.block.AralialeavesBlock;
import net.mcreator.genshinnature.block.AraliafencegateBlock;
import net.mcreator.genshinnature.block.AraliafenceBlock;
import net.mcreator.genshinnature.block.AraliadoorBlock;
import net.mcreator.genshinnature.block.AphotiumoreBlock;
import net.mcreator.genshinnature.block.AnemoshrineblockBlock;
import net.mcreator.genshinnature.block.AnemomonumentBlock;
import net.mcreator.genshinnature.block.AnemomissileBlock;
import net.mcreator.genshinnature.block.AnemohypostasisblockBlock;
import net.mcreator.genshinnature.block.AnemoculusBlock;
import net.mcreator.genshinnature.block.AnemoamberBlock;
import net.mcreator.genshinnature.block.AncientrimeBlock;
import net.mcreator.genshinnature.block.AncestralswordrackfourcoreprinciplesBlock;
import net.mcreator.genshinnature.block.AmberplushieBlock;
import net.mcreator.genshinnature.block.AloyplushieBlock;
import net.mcreator.genshinnature.block.AlbedoplushieBlock;
import net.mcreator.genshinnature.block.AetherplushieBlock;
import net.mcreator.genshinnature.GenshinNatureMod;

public class GenshinNatureModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(GenshinNatureMod.MODID);
	public static final DeferredBlock<Block> CHALLENGEBLOCKCRYO = REGISTRY.register("challengeblockcryo", ChallengeblockcryoBlock::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKCRYO_1 = REGISTRY.register("challengeblockcryo_1", Challengeblockcryo1Block::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKCRYO_2 = REGISTRY.register("challengeblockcryo_2", Challengeblockcryo2Block::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKCRYO_3 = REGISTRY.register("challengeblockcryo_3", Challengeblockcryo3Block::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKELECTRO = REGISTRY.register("challengeblockelectro", ChallengeblockelectroBlock::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKELECTRO_1 = REGISTRY.register("challengeblockelectro_1", Challengeblockelectro1Block::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKELECTRO_2 = REGISTRY.register("challengeblockelectro_2", Challengeblockelectro2Block::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKELECTRO_3 = REGISTRY.register("challengeblockelectro_3", Challengeblockelectro3Block::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKHYDRO = REGISTRY.register("challengeblockhydro", ChallengeblockhydroBlock::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKHYDRO_1 = REGISTRY.register("challengeblockhydro_1", Challengeblockhydro1Block::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKHYDRO_2 = REGISTRY.register("challengeblockhydro_2", Challengeblockhydro2Block::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKHYDRO_3 = REGISTRY.register("challengeblockhydro_3", Challengeblockhydro3Block::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKPYRO = REGISTRY.register("challengeblockpyro", ChallengeblockpyroBlock::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKPYRO_1 = REGISTRY.register("challengeblockpyro_1", Challengeblockpyro1Block::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKPYRO_2 = REGISTRY.register("challengeblockpyro_2", Challengeblockpyro2Block::new);
	public static final DeferredBlock<Block> CHALLENGEBLOCKPYRO_3 = REGISTRY.register("challengeblockpyro_3", Challengeblockpyro3Block::new);
	public static final DeferredBlock<Block> FULLSEELIETREASURE = REGISTRY.register("fullseelietreasure", FullseelietreasureBlock::new);
	public static final DeferredBlock<Block> SEELIETREASURE = REGISTRY.register("seelietreasure", SeelietreasureBlock::new);
	public static final DeferredBlock<Block> SEELIETREASURE_2 = REGISTRY.register("seelietreasure_2", Seelietreasure2Block::new);
	public static final DeferredBlock<Block> SEELIETREASURE_3 = REGISTRY.register("seelietreasure_3", Seelietreasure3Block::new);
	public static final DeferredBlock<Block> SEELIETREASURE_4 = REGISTRY.register("seelietreasure_4", Seelietreasure4Block::new);
	public static final DeferredBlock<Block> CALLALILY = REGISTRY.register("callalily", CallalilyBlock::new);
	public static final DeferredBlock<Block> CECILIA = REGISTRY.register("cecilia", CeciliaBlock::new);
	public static final DeferredBlock<Block> DENDROBIUM = REGISTRY.register("dendrobium", DendrobiumBlock::new);
	public static final DeferredBlock<Block> FLUORESCENTFUNGUS = REGISTRY.register("fluorescentfungus", FluorescentfungusBlock::new);
	public static final DeferredBlock<Block> GLAZELILY = REGISTRY.register("glazelily", GlazelilyBlock::new);
	public static final DeferredBlock<Block> NAKUWEED = REGISTRY.register("nakuweed", NakuweedBlock::new);
	public static final DeferredBlock<Block> PHILANEMOMUSHROOM = REGISTRY.register("philanemomushroom", PhilanemomushroomBlock::new);
	public static final DeferredBlock<Block> QINGXIN = REGISTRY.register("qingxin", QingxinBlock::new);
	public static final DeferredBlock<Block> JUEYUNCHILI = REGISTRY.register("jueyunchili", JueyunchiliBlock::new);
	public static final DeferredBlock<Block> SEAGANODERMA = REGISTRY.register("seaganoderma", SeaganodermaBlock::new);
	public static final DeferredBlock<Block> SILKFLOWER = REGISTRY.register("silkflower", SilkflowerBlock::new);
	public static final DeferredBlock<Block> SMALLLAMPGRASS = REGISTRY.register("smalllampgrass", SmalllampgrassBlock::new);
	public static final DeferredBlock<Block> VIOLETGRASS = REGISTRY.register("violetgrass", VioletgrassBlock::new);
	public static final DeferredBlock<Block> WINDWHEELASTER = REGISTRY.register("windwheelaster", WindwheelasterBlock::new);
	public static final DeferredBlock<Block> HORSETAIL = REGISTRY.register("horsetail", HorsetailBlock::new);
	public static final DeferredBlock<Block> LOTUSHEAD = REGISTRY.register("lotushead", LotusheadBlock::new);
	public static final DeferredBlock<Block> MATSUTAKE = REGISTRY.register("matsutake", MatsutakeBlock::new);
	public static final DeferredBlock<Block> MINT = REGISTRY.register("mint", MintBlock::new);
	public static final DeferredBlock<Block> GENSHINSEAGRASS = REGISTRY.register("genshinseagrass", GenshinseagrassBlock::new);
	public static final DeferredBlock<Block> SNAPDRAGON = REGISTRY.register("snapdragon", SnapdragonBlock::new);
	public static final DeferredBlock<Block> SWEETFLOWER = REGISTRY.register("sweetflower", SweetflowerBlock::new);
	public static final DeferredBlock<Block> GENSHINLEAVES = REGISTRY.register("genshinleaves", GenshinleavesBlock::new);
	public static final DeferredBlock<Block> STARCONCH = REGISTRY.register("starconch", StarconchBlock::new);
	public static final DeferredBlock<Block> CRYSTALCHUNK = REGISTRY.register("crystalchunk", CrystalchunkBlock::new);
	public static final DeferredBlock<Block> IRONCHUNK = REGISTRY.register("ironchunk", IronchunkBlock::new);
	public static final DeferredBlock<Block> MAGICALCRYSTALCHUNK = REGISTRY.register("magicalcrystalchunk", MagicalcrystalchunkBlock::new);
	public static final DeferredBlock<Block> STARSILVER = REGISTRY.register("starsilver", StarsilverBlock::new);
	public static final DeferredBlock<Block> WHITEIRONCHUNK = REGISTRY.register("whiteironchunk", WhiteironchunkBlock::new);
	public static final DeferredBlock<Block> ELECTROCRYSTAL = REGISTRY.register("electrocrystal", ElectrocrystalBlock::new);
	public static final DeferredBlock<Block> NOCTILUCOUSJADE = REGISTRY.register("noctilucousjade", NoctilucousjadeBlock::new);
	public static final DeferredBlock<Block> CORLAPIS = REGISTRY.register("corlapis", CorlapisBlock::new);
	public static final DeferredBlock<Block> AZHDAHASPAWNER = REGISTRY.register("azhdahaspawner", AzhdahaspawnerBlock::new);
	public static final DeferredBlock<Block> AZHDAHASPAWNER_2 = REGISTRY.register("azhdahaspawner_2", Azhdahaspawner2Block::new);
	public static final DeferredBlock<Block> AZHDAHASPAWNER_3 = REGISTRY.register("azhdahaspawner_3", Azhdahaspawner3Block::new);
	public static final DeferredBlock<Block> AZHDAHASPAWNER_4 = REGISTRY.register("azhdahaspawner_4", Azhdahaspawner4Block::new);
	public static final DeferredBlock<Block> AZHDAHASPAWNER_5 = REGISTRY.register("azhdahaspawner_5", Azhdahaspawner5Block::new);
	public static final DeferredBlock<Block> WISPSPAWNER = REGISTRY.register("wispspawner", WispspawnerBlock::new);
	public static final DeferredBlock<Block> ELECTRICBALLSPAWNER = REGISTRY.register("electricballspawner", ElectricballspawnerBlock::new);
	public static final DeferredBlock<Block> LIVINGBUBBLESPAWNER = REGISTRY.register("livingbubblespawner", LivingbubblespawnerBlock::new);
	public static final DeferredBlock<Block> AZHDAHAARENABLOCK = REGISTRY.register("azhdahaarenablock", AzhdahaarenablockBlock::new);
	public static final DeferredBlock<Block> FLORACONVERTER = REGISTRY.register("floraconverter", FloraconverterBlock::new);
	public static final DeferredBlock<Block> SAKURABLOOM = REGISTRY.register("sakurabloom", SakurabloomBlock::new);
	public static final DeferredBlock<Block> FLAMINGFLOWER = REGISTRY.register("flamingflower", FlamingflowerBlock::new);
	public static final DeferredBlock<Block> MISTFLOWER = REGISTRY.register("mistflower", MistflowerBlock::new);
	public static final DeferredBlock<Block> CRYSTALMARROW = REGISTRY.register("crystalmarrow", CrystalmarrowBlock::new);
	public static final DeferredBlock<Block> ANEMOCULUS = REGISTRY.register("anemoculus", AnemoculusBlock::new);
	public static final DeferredBlock<Block> ELECTROCULUS = REGISTRY.register("electroculus", ElectroculusBlock::new);
	public static final DeferredBlock<Block> GEOCULUS = REGISTRY.register("geoculus", GeoculusBlock::new);
	public static final DeferredBlock<Block> SOUVENIRSHOP = REGISTRY.register("souvenirshop", SouvenirshopBlock::new);
	public static final DeferredBlock<Block> PILLARSTONE = REGISTRY.register("pillarstone", PillarstoneBlock::new);
	public static final DeferredBlock<Block> WAVERIDERWAYPOINT = REGISTRY.register("waveriderwaypoint", WaveriderwaypointBlock::new);
	public static final DeferredBlock<Block> GEOHYPOSTASISBLOCK = REGISTRY.register("geohypostasisblock", GeohypostasisblockBlock::new);
	public static final DeferredBlock<Block> GREENCATPLUSHIE = REGISTRY.register("greencatplushie", GreencatplushieBlock::new);
	public static final DeferredBlock<Block> HELLCATPLUSHIE = REGISTRY.register("hellcatplushie", HellcatplushieBlock::new);
	public static final DeferredBlock<Block> ARTIFACTSBLOCK = REGISTRY.register("artifactsblock", ArtifactsblockBlock::new);
	public static final DeferredBlock<Block> CUIHUAWOOD = REGISTRY.register("cuihuawood", CuihuawoodBlock::new);
	public static final DeferredBlock<Block> CUIHUALEAVES = REGISTRY.register("cuihualeaves", CuihualeavesBlock::new);
	public static final DeferredBlock<Block> CUIHUAPLANKS = REGISTRY.register("cuihuaplanks", CuihuaplanksBlock::new);
	public static final DeferredBlock<Block> BAMBOOSEGMENT = REGISTRY.register("bamboosegment", BamboosegmentBlock::new);
	public static final DeferredBlock<Block> ARALIAWOOD = REGISTRY.register("araliawood", AraliawoodBlock::new);
	public static final DeferredBlock<Block> ARALIALEAVES = REGISTRY.register("aralialeaves", AralialeavesBlock::new);
	public static final DeferredBlock<Block> ARALIAPLANKS = REGISTRY.register("araliaplanks", AraliaplanksBlock::new);
	public static final DeferredBlock<Block> BAMBOOPLANKS = REGISTRY.register("bambooplanks", BambooplanksBlock::new);
	public static final DeferredBlock<Block> FIRWOOD = REGISTRY.register("firwood", FirwoodBlock::new);
	public static final DeferredBlock<Block> FIRLEAVES = REGISTRY.register("firleaves", FirleavesBlock::new);
	public static final DeferredBlock<Block> FIRPLANKS = REGISTRY.register("firplanks", FirplanksBlock::new);
	public static final DeferredBlock<Block> FRAGRANTCEDARWOOD = REGISTRY.register("fragrantcedarwood", FragrantcedarwoodBlock::new);
	public static final DeferredBlock<Block> FRAGRANTCEDARLEAVES = REGISTRY.register("fragrantcedarleaves", FragrantcedarleavesBlock::new);
	public static final DeferredBlock<Block> FRAGRANTCEDARPLANKS = REGISTRY.register("fragrantcedarplanks", FragrantcedarplanksBlock::new);
	public static final DeferredBlock<Block> MAPLEWOOD = REGISTRY.register("maplewood", MaplewoodBlock::new);
	public static final DeferredBlock<Block> MAPLELEAVES = REGISTRY.register("mapleleaves", MapleleavesBlock::new);
	public static final DeferredBlock<Block> MAPLEPLANKS = REGISTRY.register("mapleplanks", MapleplanksBlock::new);
	public static final DeferredBlock<Block> OTOGIWOOD = REGISTRY.register("otogiwood", OtogiwoodBlock::new);
	public static final DeferredBlock<Block> OTOGILEAVES = REGISTRY.register("otogileaves", OtogileavesBlock::new);
	public static final DeferredBlock<Block> OTOGIPLANKS = REGISTRY.register("otogiplanks", OtogiplanksBlock::new);
	public static final DeferredBlock<Block> SANDBEARERWOOD = REGISTRY.register("sandbearerwood", SandbearerwoodBlock::new);
	public static final DeferredBlock<Block> SANDBEARERLEAVES = REGISTRY.register("sandbearerleaves", SandbearerleavesBlock::new);
	public static final DeferredBlock<Block> SANDBEARERPLANKS = REGISTRY.register("sandbearerplanks", SandbearerplanksBlock::new);
	public static final DeferredBlock<Block> YUMEMIRUWOOD = REGISTRY.register("yumemiruwood", YumemiruwoodBlock::new);
	public static final DeferredBlock<Block> YUMEMIRULEAVES = REGISTRY.register("yumemiruleaves", YumemiruleavesBlock::new);
	public static final DeferredBlock<Block> YUMEMIRUPLANKS = REGISTRY.register("yumemiruplanks", YumemiruplanksBlock::new);
	public static final DeferredBlock<Block> FISHINGBLOCK = REGISTRY.register("fishingblock", FishingblockBlock::new);
	public static final DeferredBlock<Block> ANEMOHYPOSTASISBLOCK = REGISTRY.register("anemohypostasisblock", AnemohypostasisblockBlock::new);
	public static final DeferredBlock<Block> ANEMOMISSILE = REGISTRY.register("anemomissile", AnemomissileBlock::new);
	public static final DeferredBlock<Block> GOLDENWOLFLORDSTRUCTURESPAWN = REGISTRY.register("goldenwolflordstructurespawn", GoldenwolflordstructurespawnBlock::new);
	public static final DeferredBlock<Block> GOLDENATTACKERSPAWNER = REGISTRY.register("goldenattackerspawner", GoldenattackerspawnerBlock::new);
	public static final DeferredBlock<Block> GOLDENATTACKERSPAWNER_1 = REGISTRY.register("goldenattackerspawner_1", Goldenattackerspawner1Block::new);
	public static final DeferredBlock<Block> GOLDENATTACKERSPAWNER_2 = REGISTRY.register("goldenattackerspawner_2", Goldenattackerspawner2Block::new);
	public static final DeferredBlock<Block> GOLDENATTACKERSPAWNER_3 = REGISTRY.register("goldenattackerspawner_3", Goldenattackerspawner3Block::new);
	public static final DeferredBlock<Block> GOLDENATTACKERSPAWNER_4 = REGISTRY.register("goldenattackerspawner_4", Goldenattackerspawner4Block::new);
	public static final DeferredBlock<Block> APHOTIUMORE = REGISTRY.register("aphotiumore", AphotiumoreBlock::new);
	public static final DeferredBlock<Block> TOKOYOLEGUME = REGISTRY.register("tokoyolegume", TokoyolegumeBlock::new);
	public static final DeferredBlock<Block> XIAOLANTERN = REGISTRY.register("xiaolantern", XiaolanternBlock::new);
	public static final DeferredBlock<Block> HOTPOD = REGISTRY.register("hotpod", HotpodBlock::new);
	public static final DeferredBlock<Block> FLOATYSPLODY = REGISTRY.register("floatysplody", FloatysplodyBlock::new);
	public static final DeferredBlock<Block> STRAIGHTSHOOTER = REGISTRY.register("straightshooter", StraightshooterBlock::new);
	public static final DeferredBlock<Block> PYROHYPOSTASISBLOCK = REGISTRY.register("pyrohypostasisblock", PyrohypostasisblockBlock::new);
	public static final DeferredBlock<Block> WINDBLUMEFESTIVALCOMMEMORATIVEBALLOON = REGISTRY.register("windblumefestivalcommemorativeballoon", WindblumefestivalcommemorativeballoonBlock::new);
	public static final DeferredBlock<Block> ELECTROHYPOSTASISBLOCK = REGISTRY.register("electrohypostasisblock", ElectrohypostasisblockBlock::new);
	public static final DeferredBlock<Block> CUIHUAFENCE = REGISTRY.register("cuihuafence", CuihuafenceBlock::new);
	public static final DeferredBlock<Block> ARALIAFENCE = REGISTRY.register("araliafence", AraliafenceBlock::new);
	public static final DeferredBlock<Block> BAMBOOFENCE = REGISTRY.register("bamboofence", BamboofenceBlock::new);
	public static final DeferredBlock<Block> FIRFENCE = REGISTRY.register("firfence", FirfenceBlock::new);
	public static final DeferredBlock<Block> FRAGRANTCEDARFENCE = REGISTRY.register("fragrantcedarfence", FragrantcedarfenceBlock::new);
	public static final DeferredBlock<Block> MAPLEFENCE = REGISTRY.register("maplefence", MaplefenceBlock::new);
	public static final DeferredBlock<Block> OTOGIFENCE = REGISTRY.register("otogifence", OtogifenceBlock::new);
	public static final DeferredBlock<Block> SANDBEARERFENCE = REGISTRY.register("sandbearerfence", SandbearerfenceBlock::new);
	public static final DeferredBlock<Block> YUMEMIRUFENCE = REGISTRY.register("yumemirufence", YumemirufenceBlock::new);
	public static final DeferredBlock<Block> CUIHUAFENCEGATE = REGISTRY.register("cuihuafencegate", CuihuafencegateBlock::new);
	public static final DeferredBlock<Block> ARALIAFENCEGATE = REGISTRY.register("araliafencegate", AraliafencegateBlock::new);
	public static final DeferredBlock<Block> BAMBOOFENCEGATE = REGISTRY.register("bamboofencegate", BamboofencegateBlock::new);
	public static final DeferredBlock<Block> FIRFENCEGATE = REGISTRY.register("firfencegate", FirfencegateBlock::new);
	public static final DeferredBlock<Block> FRAGRANTCEDARFENCEGATE = REGISTRY.register("fragrantcedarfencegate", FragrantcedarfencegateBlock::new);
	public static final DeferredBlock<Block> MAPLEFENCEGATE = REGISTRY.register("maplefencegate", MaplefencegateBlock::new);
	public static final DeferredBlock<Block> OTOGIFENCEGATE = REGISTRY.register("otogifencegate", OtogifencegateBlock::new);
	public static final DeferredBlock<Block> SANDBEARERFENCEGATE = REGISTRY.register("sandbearerfencegate", SandbearerfencegateBlock::new);
	public static final DeferredBlock<Block> YUMEMIRUFENCEGATE = REGISTRY.register("yumemirufencegate", YumemirufencegateBlock::new);
	public static final DeferredBlock<Block> ARALIADOOR = REGISTRY.register("araliadoor", AraliadoorBlock::new);
	public static final DeferredBlock<Block> BAMBOODOOR = REGISTRY.register("bamboodoor", BamboodoorBlock::new);
	public static final DeferredBlock<Block> CUIHUADOOR = REGISTRY.register("cuihuadoor", CuihuadoorBlock::new);
	public static final DeferredBlock<Block> FIRDOOR = REGISTRY.register("firdoor", FirdoorBlock::new);
	public static final DeferredBlock<Block> FRAGRANTCEDARDOOR = REGISTRY.register("fragrantcedardoor", FragrantcedardoorBlock::new);
	public static final DeferredBlock<Block> MAPLEDOOR = REGISTRY.register("mapledoor", MapledoorBlock::new);
	public static final DeferredBlock<Block> OTOGIDOOR = REGISTRY.register("otogidoor", OtogidoorBlock::new);
	public static final DeferredBlock<Block> SANDBEARERDOOR = REGISTRY.register("sandbearerdoor", SandbearerdoorBlock::new);
	public static final DeferredBlock<Block> YUMEMIRUDOOR = REGISTRY.register("yumemirudoor", YumemirudoorBlock::new);
	public static final DeferredBlock<Block> ARALIATRAPDOOR = REGISTRY.register("araliatrapdoor", AraliatrapdoorBlock::new);
	public static final DeferredBlock<Block> BAMBOOTRAPDOOR = REGISTRY.register("bambootrapdoor", BambootrapdoorBlock::new);
	public static final DeferredBlock<Block> CUIHUATRAPDOOR = REGISTRY.register("cuihuatrapdoor", CuihuatrapdoorBlock::new);
	public static final DeferredBlock<Block> FIRTRAPDOOR = REGISTRY.register("firtrapdoor", FirtrapdoorBlock::new);
	public static final DeferredBlock<Block> FRAGRANTCEDARTRAPDOOR = REGISTRY.register("fragrantcedartrapdoor", FragrantcedartrapdoorBlock::new);
	public static final DeferredBlock<Block> MAPLETRAPDOOR = REGISTRY.register("mapletrapdoor", MapletrapdoorBlock::new);
	public static final DeferredBlock<Block> OTOGITRAPDOOR = REGISTRY.register("otogitrapdoor", OtogitrapdoorBlock::new);
	public static final DeferredBlock<Block> SANDBEARERTRAPDOOR = REGISTRY.register("sandbearertrapdoor", SandbearertrapdoorBlock::new);
	public static final DeferredBlock<Block> YUMEMIRUTRAPDOOR = REGISTRY.register("yumemirutrapdoor", YumemirutrapdoorBlock::new);
	public static final DeferredBlock<Block> ARCHAICSTONE = REGISTRY.register("archaicstone", ArchaicstoneBlock::new);
	public static final DeferredBlock<Block> SUBROSIUM = REGISTRY.register("subrosium", SubrosiumBlock::new);
	public static final DeferredBlock<Block> ANEMOMONUMENT = REGISTRY.register("anemomonument", AnemomonumentBlock::new);
	public static final DeferredBlock<Block> CRYOMONUMENT = REGISTRY.register("cryomonument", CryomonumentBlock::new);
	public static final DeferredBlock<Block> ELECTROMONUMENT = REGISTRY.register("electromonument", ElectromonumentBlock::new);
	public static final DeferredBlock<Block> GEOMONUMENT = REGISTRY.register("geomonument", GeomonumentBlock::new);
	public static final DeferredBlock<Block> HYDROMONUMENT = REGISTRY.register("hydromonument", HydromonumentBlock::new);
	public static final DeferredBlock<Block> PYROMONUMENT = REGISTRY.register("pyromonument", PyromonumentBlock::new);
	public static final DeferredBlock<Block> BLANKMONUMENT = REGISTRY.register("blankmonument", BlankmonumentBlock::new);
	public static final DeferredBlock<Block> STARSHROOM = REGISTRY.register("starshroom", StarshroomBlock::new);
	public static final DeferredBlock<Block> DARKMUD = REGISTRY.register("darkmud", DarkmudBlock::new);
	public static final DeferredBlock<Block> DARKMUDCARPET = REGISTRY.register("darkmudcarpet", DarkmudcarpetBlock::new);
	public static final DeferredBlock<Block> OOZINGCONCRETIONS = REGISTRY.register("oozingconcretions", OozingconcretionsBlock::new);
	public static final DeferredBlock<Block> OOZINGCONCRETIONSBIG = REGISTRY.register("oozingconcretionsbig", OozingconcretionsbigBlock::new);
	public static final DeferredBlock<Block> DECORATIVEOOZINGCONCRETIONS = REGISTRY.register("decorativeoozingconcretions", DecorativeoozingconcretionsBlock::new);
	public static final DeferredBlock<Block> DECORATIVEOOZINGCONCRETIONSBIG = REGISTRY.register("decorativeoozingconcretionsbig", DecorativeoozingconcretionsbigBlock::new);
	public static final DeferredBlock<Block> STARSPLINTERIRON = REGISTRY.register("starsplinteriron", StarsplinterironBlock::new);
	public static final DeferredBlock<Block> EVERNIGHTBLAZESHRUB = REGISTRY.register("evernightblazeshrub", EvernightblazeshrubBlock::new);
	public static final DeferredBlock<Block> EVERNIGHTGLITTERBOUGH = REGISTRY.register("evernightglitterbough", EvernightglitterboughBlock::new);
	public static final DeferredBlock<Block> SCARLETSCENTEDFANDANCE = REGISTRY.register("scarletscentedfandance", ScarletscentedfandanceBlock::new);
	public static final DeferredBlock<Block> OFPROMISESUNKEPTTHENIGHTFLOWERSSPEAK = REGISTRY.register("ofpromisesunkeptthenightflowersspeak", OfpromisesunkeptthenightflowersspeakBlock::new);
	public static final DeferredBlock<Block> MELANCHOLYTHEDEWGRASSSHADOWING = REGISTRY.register("melancholythedewgrassshadowing", MelancholythedewgrassshadowingBlock::new);
	public static final DeferredBlock<Block> THEASTERSSIGH = REGISTRY.register("theasterssigh", TheasterssighBlock::new);
	public static final DeferredBlock<Block> THRICEDYEDCRIMSONSNOWMELT = REGISTRY.register("thricedyedcrimsonsnowmelt", ThricedyedcrimsonsnowmeltBlock::new);
	public static final DeferredBlock<Block> THROUGHTHEWHITEFOAMTHEJADEBUTTERFLYSOARS = REGISTRY.register("throughthewhitefoamthejadebutterflysoars", ThroughthewhitefoamthejadebutterflysoarsBlock::new);
	public static final DeferredBlock<Block> TREESOFAZUREJADE = REGISTRY.register("treesofazurejade", TreesofazurejadeBlock::new);
	public static final DeferredBlock<Block> CRIMSONAGATEORE = REGISTRY.register("crimsonagateore", CrimsonagateoreBlock::new);
	public static final DeferredBlock<Block> RUINBRAZIER = REGISTRY.register("ruinbrazier", RuinbrazierBlock::new);
	public static final DeferredBlock<Block> PYROBOOMBLOSSOM = REGISTRY.register("pyroboomblossom", PyroboomblossomBlock::new);
	public static final DeferredBlock<Block> ELECTROBOOMBLOSSOM = REGISTRY.register("electroboomblossom", ElectroboomblossomBlock::new);
	public static final DeferredBlock<Block> CRYOBOOMBLOSSOM = REGISTRY.register("cryoboomblossom", CryoboomblossomBlock::new);
	public static final DeferredBlock<Block> LUMENSPARORE = REGISTRY.register("lumensparore", LumensparoreBlock::new);
	public static final DeferredBlock<Block> MYSTERIOUSCARVING = REGISTRY.register("mysteriouscarving", MysteriouscarvingBlock::new);
	public static final DeferredBlock<Block> MIASMICTUMORSPAWNBLOCK = REGISTRY.register("miasmictumorspawnblock", MiasmictumorspawnblockBlock::new);
	public static final DeferredBlock<Block> SHOOTINGBUBBLE = REGISTRY.register("shootingbubble", ShootingbubbleBlock::new);
	public static final DeferredBlock<Block> ANCESTRALSWORDRACKFOURCOREPRINCIPLES = REGISTRY.register("ancestralswordrackfourcoreprinciples", AncestralswordrackfourcoreprinciplesBlock::new);
	public static final DeferredBlock<Block> BAMBOOOUTDOORTABLE = REGISTRY.register("bamboooutdoortable", BamboooutdoortableBlock::new);
	public static final DeferredBlock<Block> BLUECAFECUP = REGISTRY.register("bluecafecup", BluecafecupBlock::new);
	public static final DeferredBlock<Block> CAFEPOT = REGISTRY.register("cafepot", CafepotBlock::new);
	public static final DeferredBlock<Block> CLEARBLUEAFTERNOON = REGISTRY.register("clearblueafternoon", ClearblueafternoonBlock::new);
	public static final DeferredBlock<Block> CRADLEOFFLOWERS = REGISTRY.register("cradleofflowers", CradleofflowersBlock::new);
	public static final DeferredBlock<Block> CRIMSONARDOR = REGISTRY.register("crimsonardor", CrimsonardorBlock::new);
	public static final DeferredBlock<Block> CRUDEDOUBLEDECKERPALLET = REGISTRY.register("crudedoubledeckerpallet", CrudedoubledeckerpalletBlock::new);
	public static final DeferredBlock<Block> EMBROIDEREDLANTERNLOFTYGRANDEUR = REGISTRY.register("embroideredlanternloftygrandeur", EmbroideredlanternloftygrandeurBlock::new);
	public static final DeferredBlock<Block> EUPHONIUMUNBOUNDWINDING = REGISTRY.register("euphoniumunboundwinding", EuphoniumunboundwindingBlock::new);
	public static final DeferredBlock<Block> FOUNDATIONSOFSTONEDOUBLETIME = REGISTRY.register("foundationsofstonedoubletime", FoundationsofstonedoubletimeBlock::new);
	public static final DeferredBlock<Block> FOUNDATIONSOFSTONEPATHOFCULTIVATION = REGISTRY.register("foundationsofstonepathofcultivation", FoundationsofstonepathofcultivationBlock::new);
	public static final DeferredBlock<Block> FRAGRANTCEDARVEGETABLERACK = REGISTRY.register("fragrantcedarvegetablerack", FragrantcedarvegetablerackBlock::new);
	public static final DeferredBlock<Block> GOOGOLCHAIR = REGISTRY.register("googolchair", GoogolchairBlock::new);
	public static final DeferredBlock<Block> GOOGOLTABLE = REGISTRY.register("googoltable", GoogoltableBlock::new);
	public static final DeferredBlock<Block> GREENCAFECUP = REGISTRY.register("greencafecup", GreencafecupBlock::new);
	public static final DeferredBlock<Block> GUOBAPLUSHIE = REGISTRY.register("guobaplushie", GuobaplushieBlock::new);
	public static final DeferredBlock<Block> HOMEAWAYFROMHOME = REGISTRY.register("homeawayfromhome", HomeawayfromhomeBlock::new);
	public static final DeferredBlock<Block> MAPLEWOODCHANDELIERILLUME = REGISTRY.register("maplewoodchandelierillume", MaplewoodchandelierillumeBlock::new);
	public static final DeferredBlock<Block> MAPLEWOODRITUALDRUMFESTIVEMUSIC = REGISTRY.register("maplewoodritualdrumfestivemusic", MaplewoodritualdrumfestivemusicBlock::new);
	public static final DeferredBlock<Block> NIGHTOFTHEPARTYPUMPKINS = REGISTRY.register("nightofthepartypumpkins", NightofthepartypumpkinsBlock::new);
	public static final DeferredBlock<Block> OTOGIRAKUSHISQUARESTOOL = REGISTRY.register("otogirakushisquarestool", OtogirakushisquarestoolBlock::new);
	public static final DeferredBlock<Block> OTOGIRAKUSHISQUARETABLE = REGISTRY.register("otogirakushisquaretable", OtogirakushisquaretableBlock::new);
	public static final DeferredBlock<Block> CRYSTALFLYLAMP = REGISTRY.register("crystalflylamp", CrystalflylampBlock::new);
	public static final DeferredBlock<Block> PINEDININGCHAIR = REGISTRY.register("pinediningchair", PinediningchairBlock::new);
	public static final DeferredBlock<Block> PINEBACKEDTEACHAIR = REGISTRY.register("pinebackedteachair", PinebackedteachairBlock::new);
	public static final DeferredBlock<Block> REDCAFECUP = REGISTRY.register("redcafecup", RedcafecupBlock::new);
	public static final DeferredBlock<Block> REDPINEWOODROUNDSTOOL = REGISTRY.register("redpinewoodroundstool", RedpinewoodroundstoolBlock::new);
	public static final DeferredBlock<Block> SMOOTHSTONEBENCH = REGISTRY.register("smoothstonebench", SmoothstonebenchBlock::new);
	public static final DeferredBlock<Block> SMOOTHWOODENBENCH = REGISTRY.register("smoothwoodenbench", SmoothwoodenbenchBlock::new);
	public static final DeferredBlock<Block> SQUAREYUMEMIRUSTOOL = REGISTRY.register("squareyumemirustool", SquareyumemirustoolBlock::new);
	public static final DeferredBlock<Block> TEAHOUSECUSHIONNIGHTWOVEN = REGISTRY.register("teahousecushionnightwoven", TeahousecushionnightwovenBlock::new);
	public static final DeferredBlock<Block> TEAHOUSEROUNDSTOOLPAINPOINTREDUCTION = REGISTRY.register("teahouseroundstoolpainpointreduction", TeahouseroundstoolpainpointreductionBlock::new);
	public static final DeferredBlock<Block> THEBLUEOCEANSTREASURE = REGISTRY.register("theblueoceanstreasure", TheblueoceanstreasureBlock::new);
	public static final DeferredBlock<Block> BLOATTYFLOATTY = REGISTRY.register("bloattyfloatty", BloattyfloattyBlock::new);
	public static final DeferredBlock<Block> BLOATTYFLOATTYEXPLODED = REGISTRY.register("bloattyfloattyexploded", BloattyfloattyexplodedBlock::new);
	public static final DeferredBlock<Block> LIULIPAVILIONSANDBEARERFLOORLAMP = REGISTRY.register("liulipavilionsandbearerfloorlamp", LiulipavilionsandbearerfloorlampBlock::new);
	public static final DeferredBlock<Block> TRUSTYPORTABLELAMP = REGISTRY.register("trustyportablelamp", TrustyportablelampBlock::new);
	public static final DeferredBlock<Block> ROCKPILLARPEARL = REGISTRY.register("rockpillarpearl", RockpillarpearlBlock::new);
	public static final DeferredBlock<Block> CRYOHYPOSTASISBLOCK = REGISTRY.register("cryohypostasisblock", CryohypostasisblockBlock::new);
	public static final DeferredBlock<Block> CAKEFORTRAVELER = REGISTRY.register("cakefortraveler", CakefortravelerBlock::new);
	public static final DeferredBlock<Block> CAKEFORTRAVELER_2 = REGISTRY.register("cakefortraveler_2", Cakefortraveler2Block::new);
	public static final DeferredBlock<Block> CAKEFORTRAVELER_3 = REGISTRY.register("cakefortraveler_3", Cakefortraveler3Block::new);
	public static final DeferredBlock<Block> GLASSSHIELD = REGISTRY.register("glassshield", GlassshieldBlock::new);
	public static final DeferredBlock<Block> CRIMSONAGATEBLOCK = REGISTRY.register("crimsonagateblock", CrimsonagateblockBlock::new);
	public static final DeferredBlock<Block> LUMENSPARBLOCK = REGISTRY.register("lumensparblock", LumensparblockBlock::new);
	public static final DeferredBlock<Block> TROUNCEBLOSSOM = REGISTRY.register("trounceblossom", TrounceblossomBlock::new);
	public static final DeferredBlock<Block> BAALSTATUE = REGISTRY.register("baalstatue", BaalstatueBlock::new);
	public static final DeferredBlock<Block> ELECTROSHOOT = REGISTRY.register("electroshoot", ElectroshootBlock::new);
	public static final DeferredBlock<Block> STRANGETOOTH = REGISTRY.register("strangetooth", StrangetoothBlock::new);
	public static final DeferredBlock<Block> HYDROHYPOSTASISBLOCK = REGISTRY.register("hydrohypostasisblock", HydrohypostasisblockBlock::new);
	public static final DeferredBlock<Block> PLUSHIESLOOTBOX = REGISTRY.register("plushieslootbox", PlushieslootboxBlock::new);
	public static final DeferredBlock<Block> PERPETUALMECHANICALARRAYBLOCK = REGISTRY.register("perpetualmechanicalarrayblock", PerpetualmechanicalarrayblockBlock::new);
	public static final DeferredBlock<Block> ALBEDOPLUSHIE = REGISTRY.register("albedoplushie", AlbedoplushieBlock::new);
	public static final DeferredBlock<Block> ALOYPLUSHIE = REGISTRY.register("aloyplushie", AloyplushieBlock::new);
	public static final DeferredBlock<Block> AMBERPLUSHIE = REGISTRY.register("amberplushie", AmberplushieBlock::new);
	public static final DeferredBlock<Block> AYAKAPLUSHIE = REGISTRY.register("ayakaplushie", AyakaplushieBlock::new);
	public static final DeferredBlock<Block> AYATOPLUSHIE = REGISTRY.register("ayatoplushie", AyatoplushieBlock::new);
	public static final DeferredBlock<Block> BARBARAPLUSHIE = REGISTRY.register("barbaraplushie", BarbaraplushieBlock::new);
	public static final DeferredBlock<Block> BEIDOUPLUSHIE = REGISTRY.register("beidouplushie", BeidouplushieBlock::new);
	public static final DeferredBlock<Block> BENNETTPLUSHIE = REGISTRY.register("bennettplushie", BennettplushieBlock::new);
	public static final DeferredBlock<Block> CHONGYUNPLUSHIE = REGISTRY.register("chongyunplushie", ChongyunplushieBlock::new);
	public static final DeferredBlock<Block> DILUCPLUSHIE = REGISTRY.register("dilucplushie", DilucplushieBlock::new);
	public static final DeferredBlock<Block> DIONAPLUSHIE = REGISTRY.register("dionaplushie", DionaplushieBlock::new);
	public static final DeferredBlock<Block> EULAPLUSHIE = REGISTRY.register("eulaplushie", EulaplushieBlock::new);
	public static final DeferredBlock<Block> FISCHLPLUSHIE = REGISTRY.register("fischlplushie", FischlplushieBlock::new);
	public static final DeferredBlock<Block> GANYUPLUSHIE = REGISTRY.register("ganyuplushie", GanyuplushieBlock::new);
	public static final DeferredBlock<Block> GOROUPLUSHIE = REGISTRY.register("gorouplushie", GorouplushieBlock::new);
	public static final DeferredBlock<Block> HUTAOPLUSHIE = REGISTRY.register("hutaoplushie", HutaoplushieBlock::new);
	public static final DeferredBlock<Block> ITTOPLUSHIE = REGISTRY.register("ittoplushie", IttoplushieBlock::new);
	public static final DeferredBlock<Block> JEANPLUSHIE = REGISTRY.register("jeanplushie", JeanplushieBlock::new);
	public static final DeferredBlock<Block> KAEYAPLUSHIE = REGISTRY.register("kaeyaplushie", KaeyaplushieBlock::new);
	public static final DeferredBlock<Block> KAZUHAPLUSHIE = REGISTRY.register("kazuhaplushie", KazuhaplushieBlock::new);
	public static final DeferredBlock<Block> KEQINGPLUSHIE = REGISTRY.register("keqingplushie", KeqingplushieBlock::new);
	public static final DeferredBlock<Block> KLEEPLUSHIE = REGISTRY.register("kleeplushie", KleeplushieBlock::new);
	public static final DeferredBlock<Block> KOKOMIPLUSHIE = REGISTRY.register("kokomiplushie", KokomiplushieBlock::new);
	public static final DeferredBlock<Block> MONAPLUSHIE = REGISTRY.register("monaplushie", MonaplushieBlock::new);
	public static final DeferredBlock<Block> NOELLEPLUSHIE = REGISTRY.register("noelleplushie", NoelleplushieBlock::new);
	public static final DeferredBlock<Block> ROSARIAPLUSHIE = REGISTRY.register("rosariaplushie", RosariaplushieBlock::new);
	public static final DeferredBlock<Block> SAYUPLUSHIE = REGISTRY.register("sayuplushie", SayuplushieBlock::new);
	public static final DeferredBlock<Block> SUCROSEPLUSHIE = REGISTRY.register("sucroseplushie", SucroseplushieBlock::new);
	public static final DeferredBlock<Block> TARTAGLIAPLUSHIE = REGISTRY.register("tartagliaplushie", TartagliaplushieBlock::new);
	public static final DeferredBlock<Block> VENTIPLUSHIE = REGISTRY.register("ventiplushie", VentiplushieBlock::new);
	public static final DeferredBlock<Block> XIANGLINGPLUSHIE = REGISTRY.register("xianglingplushie", XianglingplushieBlock::new);
	public static final DeferredBlock<Block> XIAOPLUSHIE = REGISTRY.register("xiaoplushie", XiaoplushieBlock::new);
	public static final DeferredBlock<Block> XINGQIUPLUSHIE = REGISTRY.register("xingqiuplushie", XingqiuplushieBlock::new);
	public static final DeferredBlock<Block> YAEMIKOPLUSHIE = REGISTRY.register("yaemikoplushie", YaemikoplushieBlock::new);
	public static final DeferredBlock<Block> YANFEIPLUSHIE = REGISTRY.register("yanfeiplushie", YanfeiplushieBlock::new);
	public static final DeferredBlock<Block> YOIMIYAPLUSHIE = REGISTRY.register("yoimiyaplushie", YoimiyaplushieBlock::new);
	public static final DeferredBlock<Block> ZHONGLIPLUSHIE = REGISTRY.register("zhongliplushie", ZhongliplushieBlock::new);
	public static final DeferredBlock<Block> RUINSERPENTSPAWNER = REGISTRY.register("ruinserpentspawner", RuinserpentspawnerBlock::new);
	public static final DeferredBlock<Block> RUINSERPENTSPAWNER_1 = REGISTRY.register("ruinserpentspawner_1", Ruinserpentspawner1Block::new);
	public static final DeferredBlock<Block> RUINSERPENTSPAWNER_2 = REGISTRY.register("ruinserpentspawner_2", Ruinserpentspawner2Block::new);
	public static final DeferredBlock<Block> RUINSERPENTSPAWNER_3 = REGISTRY.register("ruinserpentspawner_3", Ruinserpentspawner3Block::new);
	public static final DeferredBlock<Block> THOMAPLUSHIE = REGISTRY.register("thomaplushie", ThomaplushieBlock::new);
	public static final DeferredBlock<Block> LISAPLUSHIE = REGISTRY.register("lisaplushie", LisaplushieBlock::new);
	public static final DeferredBlock<Block> RAZORPLUSHIE = REGISTRY.register("razorplushie", RazorplushieBlock::new);
	public static final DeferredBlock<Block> RAIDENPLUSHIE = REGISTRY.register("raidenplushie", RaidenplushieBlock::new);
	public static final DeferredBlock<Block> QIQIPLUSHIE = REGISTRY.register("qiqiplushie", QiqiplushieBlock::new);
	public static final DeferredBlock<Block> NINGGUANGPLUSHIE = REGISTRY.register("ningguangplushie", NingguangplushieBlock::new);
	public static final DeferredBlock<Block> DAINSLEIFPLUSHIE = REGISTRY.register("dainsleifplushie", DainsleifplushieBlock::new);
	public static final DeferredBlock<Block> SHENHEPLUSHIE = REGISTRY.register("shenheplushie", ShenheplushieBlock::new);
	public static final DeferredBlock<Block> XINYANPLUSHIE = REGISTRY.register("xinyanplushie", XinyanplushieBlock::new);
	public static final DeferredBlock<Block> KUKIPLUSHIE = REGISTRY.register("kukiplushie", KukiplushieBlock::new);
	public static final DeferredBlock<Block> YELANPLUSHIE = REGISTRY.register("yelanplushie", YelanplushieBlock::new);
	public static final DeferredBlock<Block> YUNJINPLUSHIE = REGISTRY.register("yunjinplushie", YunjinplushieBlock::new);
	public static final DeferredBlock<Block> LUMINEPLUSHIE = REGISTRY.register("lumineplushie", LumineplushieBlock::new);
	public static final DeferredBlock<Block> AETHERPLUSHIE = REGISTRY.register("aetherplushie", AetherplushieBlock::new);
	public static final DeferredBlock<Block> HEIZOUPLUSHIE = REGISTRY.register("heizouplushie", HeizouplushieBlock::new);
	public static final DeferredBlock<Block> SARAPLUSHIE = REGISTRY.register("saraplushie", SaraplushieBlock::new);
	public static final DeferredBlock<Block> PAIMONPLUSHIE = REGISTRY.register("paimonplushie", PaimonplushieBlock::new);
	public static final DeferredBlock<Block> ARALIASTAIRS = REGISTRY.register("araliastairs", AraliastairsBlock::new);
	public static final DeferredBlock<Block> ARALIASLAB = REGISTRY.register("araliaslab", AraliaslabBlock::new);
	public static final DeferredBlock<Block> BAMBOOSTAIRS = REGISTRY.register("bamboostairs", BamboostairsBlock::new);
	public static final DeferredBlock<Block> BAMBOOSLAB = REGISTRY.register("bambooslab", BambooslabBlock::new);
	public static final DeferredBlock<Block> CUIHUASTAIRS = REGISTRY.register("cuihuastairs", CuihuastairsBlock::new);
	public static final DeferredBlock<Block> CUIHUASLAB = REGISTRY.register("cuihuaslab", CuihuaslabBlock::new);
	public static final DeferredBlock<Block> FIRSTAIRS = REGISTRY.register("firstairs", FirstairsBlock::new);
	public static final DeferredBlock<Block> FIRSLAB = REGISTRY.register("firslab", FirslabBlock::new);
	public static final DeferredBlock<Block> FRAGRANTCEDARSTAIRS = REGISTRY.register("fragrantcedarstairs", FragrantcedarstairsBlock::new);
	public static final DeferredBlock<Block> FRAGRANTCEDARSLAB = REGISTRY.register("fragrantcedarslab", FragrantcedarslabBlock::new);
	public static final DeferredBlock<Block> MAPLESTAIRS = REGISTRY.register("maplestairs", MaplestairsBlock::new);
	public static final DeferredBlock<Block> MAPLESLAB = REGISTRY.register("mapleslab", MapleslabBlock::new);
	public static final DeferredBlock<Block> OTOGISTAIRS = REGISTRY.register("otogistairs", OtogistairsBlock::new);
	public static final DeferredBlock<Block> OTOGISLAB = REGISTRY.register("otogislab", OtogislabBlock::new);
	public static final DeferredBlock<Block> SANDBEARERSTAIRS = REGISTRY.register("sandbearerstairs", SandbearerstairsBlock::new);
	public static final DeferredBlock<Block> SANDBEARERSLAB = REGISTRY.register("sandbearerslab", SandbearerslabBlock::new);
	public static final DeferredBlock<Block> YUMEMIRUSTAIRS = REGISTRY.register("yumemirustairs", YumemirustairsBlock::new);
	public static final DeferredBlock<Block> YUMEMIRUSLAB = REGISTRY.register("yumemiruslab", YumemiruslabBlock::new);
	public static final DeferredBlock<Block> MAUVELUTESEDGESHROOM = REGISTRY.register("mauvelutesedgeshroom", MauvelutesedgeshroomBlock::new);
	public static final DeferredBlock<Block> EVERLASTINGINCENSE = REGISTRY.register("everlastingincense", EverlastingincenseBlock::new);
	public static final DeferredBlock<Block> COLLEIPLUSHIE = REGISTRY.register("colleiplushie", ColleiplushieBlock::new);
	public static final DeferredBlock<Block> TIGHNARIPLUSHIE = REGISTRY.register("tighnariplushie", TighnariplushieBlock::new);
	public static final DeferredBlock<Block> DORIPLUSHIE = REGISTRY.register("doriplushie", DoriplushieBlock::new);
	public static final DeferredBlock<Block> WONDROUSLOVELYFLOWER = REGISTRY.register("wondrouslovelyflower", WondrouslovelyflowerBlock::new);
	public static final DeferredBlock<Block> DENDROCULUS = REGISTRY.register("dendroculus", DendroculusBlock::new);
	public static final DeferredBlock<Block> DENDROMONUMENT = REGISTRY.register("dendromonument", DendromonumentBlock::new);
	public static final DeferredBlock<Block> HYDROTILE = REGISTRY.register("hydrotile", HydrotileBlock::new);
	public static final DeferredBlock<Block> LUMENSTONE = REGISTRY.register("lumenstone", LumenstoneBlock::new);
	public static final DeferredBlock<Block> LUMENSTONE_5 = REGISTRY.register("lumenstone_5", Lumenstone5Block::new);
	public static final DeferredBlock<Block> LUMENSTONE_10 = REGISTRY.register("lumenstone_10", Lumenstone10Block::new);
	public static final DeferredBlock<Block> LUMENSTONE_15 = REGISTRY.register("lumenstone_15", Lumenstone15Block::new);
	public static final DeferredBlock<Block> TIMEDCOBBLESTONE = REGISTRY.register("timedcobblestone", TimedcobblestoneBlock::new);
	public static final DeferredBlock<Block> TIMEDOBSIDIAN = REGISTRY.register("timedobsidian", TimedobsidianBlock::new);
	public static final DeferredBlock<Block> TIMEDICE = REGISTRY.register("timedice", TimediceBlock::new);
	public static final DeferredBlock<Block> SCARLETQUARTZ = REGISTRY.register("scarletquartz", ScarletquartzBlock::new);
	public static final DeferredBlock<Block> ANCIENTRIME = REGISTRY.register("ancientrime", AncientrimeBlock::new);
	public static final DeferredBlock<Block> ANEMOAMBER = REGISTRY.register("anemoamber", AnemoamberBlock::new);
	public static final DeferredBlock<Block> HYDROAMBER = REGISTRY.register("hydroamber", HydroamberBlock::new);
	public static final DeferredBlock<Block> ANEMOSHRINEBLOCK = REGISTRY.register("anemoshrineblock", AnemoshrineblockBlock::new);
	public static final DeferredBlock<Block> ELECTROSHRINEBLOCK = REGISTRY.register("electroshrineblock", ElectroshrineblockBlock::new);
	public static final DeferredBlock<Block> GEOSHRINEBLOCK = REGISTRY.register("geoshrineblock", GeoshrineblockBlock::new);
	public static final DeferredBlock<Block> DENDROSHRINEBLOCK = REGISTRY.register("dendroshrineblock", DendroshrineblockBlock::new);
	public static final DeferredBlock<Block> DENDROCORE = REGISTRY.register("dendrocore", DendrocoreBlock::new);
	public static final DeferredBlock<Block> RADIANTSPINCRYSTAL = REGISTRY.register("radiantspincrystal", RadiantspincrystalBlock::new);
	public static final DeferredBlock<Block> BIRDNEST = REGISTRY.register("birdnest", BirdnestBlock::new);
	public static final DeferredBlock<Block> SUMERUROSE = REGISTRY.register("sumerurose", SumeruroseBlock::new);
	public static final DeferredBlock<Block> PADISARAH = REGISTRY.register("padisarah", PadisarahBlock::new);
	public static final DeferredBlock<Block> WITHERINGEXPANDING = REGISTRY.register("witheringexpanding", WitheringexpandingBlock::new);
	public static final DeferredBlock<Block> WITHERINGEXPANDING_2 = REGISTRY.register("witheringexpanding_2", Witheringexpanding2Block::new);
	public static final DeferredBlock<Block> WITHERINGEXPANDING_3 = REGISTRY.register("witheringexpanding_3", Witheringexpanding3Block::new);
	public static final DeferredBlock<Block> WITHERINGEXPANDING_4 = REGISTRY.register("witheringexpanding_4", Witheringexpanding4Block::new);
	public static final DeferredBlock<Block> WITHERINGSTOPPED = REGISTRY.register("witheringstopped", WitheringstoppedBlock::new);
	public static final DeferredBlock<Block> VIPARYAS = REGISTRY.register("viparyas", ViparyasBlock::new);
	public static final DeferredBlock<Block> NILOTPALALOTUS = REGISTRY.register("nilotpalalotus", NilotpalalotusBlock::new);
	public static final DeferredBlock<Block> KALPALATALOTUS = REGISTRY.register("kalpalatalotus", KalpalatalotusBlock::new);
	public static final DeferredBlock<Block> CANDLEOFLIFE = REGISTRY.register("candleoflife", CandleoflifeBlock::new);
	public static final DeferredBlock<Block> RUKKHASHAVAMUSHROOMS = REGISTRY.register("rukkhashavamushrooms", RukkhashavamushroomsBlock::new);
	public static final DeferredBlock<Block> MOBSPAWNERGENSHIN = REGISTRY.register("mobspawnergenshin", MobspawnergenshinBlock::new);
	public static final DeferredBlock<Block> DENDROBOOMBLOSSOM = REGISTRY.register("dendroboomblossom", DendroboomblossomBlock::new);
	public static final DeferredBlock<Block> NILOUPLUSHIE = REGISTRY.register("nilouplushie", NilouplushieBlock::new);
	public static final DeferredBlock<Block> CYNOPLUSHIE = REGISTRY.register("cynoplushie", CynoplushieBlock::new);
	public static final DeferredBlock<Block> CANDACEPLUSHIE = REGISTRY.register("candaceplushie", CandaceplushieBlock::new);
	public static final DeferredBlock<Block> SILAPNA = REGISTRY.register("silapna", SilapnaBlock::new);
	public static final DeferredBlock<Block> BARSAMFLOWER = REGISTRY.register("barsamflower", BarsamflowerBlock::new);
	public static final DeferredBlock<Block> YAJNAGRASS = REGISTRY.register("yajnagrass", YajnagrassBlock::new);
	public static final DeferredBlock<Block> ZOHRAHMUSHROOM = REGISTRY.register("zohrahmushroom", ZohrahmushroomBlock::new);
	public static final DeferredBlock<Block> SPAWNPRIMALTEMPLE = REGISTRY.register("spawnprimaltemple", SpawnprimaltempleBlock::new);
	public static final DeferredBlock<Block> CHILDESPAWNER = REGISTRY.register("childespawner", ChildespawnerBlock::new);
	public static final DeferredBlock<Block> GOLDENHOUSESPAWNER = REGISTRY.register("goldenhousespawner", GoldenhousespawnerBlock::new);
	public static final DeferredBlock<Block> CHILDESPAWNER_1 = REGISTRY.register("childespawner_1", Childespawner1Block::new);
	public static final DeferredBlock<Block> CHILDESPAWNER_2 = REGISTRY.register("childespawner_2", Childespawner2Block::new);
	public static final DeferredBlock<Block> GOLDENROSESEEDS = REGISTRY.register("goldenroseseeds", GoldenroseseedsBlock::new);
	public static final DeferredBlock<Block> LEYLINEORE = REGISTRY.register("leylineore", LeylineoreBlock::new);
	public static final DeferredBlock<Block> LEYLINEOREEND = REGISTRY.register("leylineoreend", LeylineoreendBlock::new);
	public static final DeferredBlock<Block> LEYLINEMINERALBLOCK = REGISTRY.register("leylinemineralblock", LeylinemineralblockBlock::new);
	public static final DeferredBlock<Block> TALENTSBLOCK = REGISTRY.register("talentsblock", TalentsblockBlock::new);
	public static final DeferredBlock<Block> NAHIDAPLUSHIE = REGISTRY.register("nahidaplushie", NahidaplushieBlock::new);
	public static final DeferredBlock<Block> LAYLAPLUSHIE = REGISTRY.register("laylaplushie", LaylaplushieBlock::new);
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
