name: Java CI with Gradle

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment (PR)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
          echo "LAST_COMMIT_SHA=$calculatedSha" >> ${GITHUB_ENV}

      - name: Setup Environment (Push)
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "LAST_COMMIT_SHA=$calculatedSha" >> ${GITHUB_ENV}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: gradle build

      - name: Rename
        run: mv build/libs/modid-1.0.jar build/libs/genshin-nature-${{ env.LAST_COMMIT_SHA }}.jar

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: genshin-nature-${{ env.LAST_COMMIT_SHA }}
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
